// Exercise the deployed handler against isolated Auth and database dependencies.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const {webcrypto:crypto,randomUUID}=require('node:crypto');
const transpile=s=>ts.transpileModule(s,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
const retention={exports:{}};vm.runInNewContext(transpile(fs.readFileSync('lib/retention.ts','utf8')),{exports:retention.exports});
const sha=async s=>Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))).toString('hex');
async function fixture(){
 let handler;const users=[],members=[],sessions=[],calls=[],setupToken='s'.repeat(64),setup={id:1,token_hash:await sha(setupToken),used_at:null,expires_at:'2099-01-01T00:00:00Z'};
 function member(username,role='admin',active=true){const u={id:randomUUID(),email:randomUUID()+'@internal.invalid',password:'initial-pass-1234'};users.push(u);const m={user_id:u.id,email:u.email,username,role,active,must_change_password:false,sessions_valid_after:'1970-01-01T00:00:00Z'};members.push(m);return m;}
 function session(m){const s={id:randomUUID(),user_id:m.user_id,created_at:new Date().toISOString()};sessions.push(s);const token='header.'+Buffer.from(JSON.stringify({sub:m.user_id,session_id:s.id})).toString('base64url')+'.signature';s.token=token;return token;}
 const owner=member('admin','owner'),staff=member('equipe');
 const catalogDb={yp_products:[],yp_flavors:[],yp_lines:[]},deletion={deleted:true};
 const fakeFetch=async(url,init={})=>{
  const u=new URL(url),p=u.pathname,b=init.body?JSON.parse(init.body):{},method=init.method||'GET';calls.push({path:p,method,body:b});
  if(p==='/auth/v1/token'){const user=users.find(x=>x.email===b.email&&x.password===b.password);if(!user)return Response.json({error:'invalid'},{status:400});const m=members.find(x=>x.user_id===user.id),token=session(m||{user_id:user.id});return Response.json({access_token:token,refresh_token:'refresh',expires_in:3600,user:{id:user.id,email:user.email}});}
  if(p==='/auth/v1/user'){const token=init.headers.Authorization?.replace('Bearer ',''),s=sessions.find(x=>x.token===token);return s?Response.json({id:s.user_id}):Response.json({error:'invalid'},{status:401});}
  if(p==='/auth/v1/admin/users'&&method==='POST'){const user={id:randomUUID(),...b};users.push(user);return Response.json(user);}
  if(p.startsWith('/auth/v1/admin/users/')){const id=p.split('/').pop(),user=users.find(x=>x.id===id);if(method==='DELETE')users.splice(users.indexOf(user),1);if(method==='PUT')Object.assign(user,b);return Response.json(user||{});}
  if(p==='/rest/v1/rpc/yp_delete_catalog_item')return Response.json(deletion);
  if(p==='/rest/v1/rpc/yp_check_rate')return Response.json(true);
  if(p==='/rest/v1/rpc/yp_admin_session_valid'){const s=sessions.find(x=>x.id===b.p_session&&x.user_id===b.p_user),m=members.find(x=>x.user_id===b.p_user);return Response.json(!!s&&!!m?.active&&s.created_at>m.sessions_valid_after);}
  if(p==='/rest/v1/rpc/yp_claim_owner'){if(members.length||setup.used_at||setup.token_hash!==b.p_hash||Date.parse(setup.expires_at)<Date.now())return Response.json(false);members.push({user_id:b.p_user,email:b.p_email,username:'admin',role:'owner',active:true,must_change_password:true,sessions_valid_after:'1970-01-01T00:00:00Z'});setup.used_at=new Date().toISOString();return Response.json(true);}
  if(p.startsWith('/rest/v1/')){const table=p.split('/').pop(),all=table==='yp_admins'?members:table==='yp_setup'?[setup]:table==='yp_settings'?[{id:1}]:(catalogDb[table]||[]);let rows=all.filter(row=>[...u.searchParams].every(([k,v])=>v.startsWith('eq.')?String(row[k])===v.slice(3):v==='is.null'?row[k]===null:v.startsWith('gt.')?row[k]>v.slice(3):true));
   if(method==='POST'){if(table==='yp_admins'){if(members.some(m=>m.username===b.username))return Response.json({error:'duplicate'},{status:409});const m={active:true,must_change_password:false,sessions_valid_after:'1970-01-01T00:00:00Z',...b};members.push(m);rows=[m];}}
   if(method==='PATCH')rows.forEach(x=>Object.assign(x,b));
   const select=u.searchParams.get('select');return Response.json(select?rows.map(r=>Object.fromEntries(select.split(',').map(k=>[k,r[k]]))):rows);
  }throw new Error('Unexpected '+method+' '+p);
 };
 const source=fs.readFileSync('supabase/functions/order-portal/index.ts','utf8').replace(/^import .*;$/gm,'');
 vm.runInNewContext(transpile(source),{Deno:{env:{get:k=>k==='SUPABASE_URL'?'https://isolated.invalid':'secret'},serve:f=>handler=f},...retention.exports,crypto,TextEncoder,TextDecoder,Uint8Array,Request,Response,URL,atob,fetch:fakeFetch});
 async function call(body,token,expected=200){const r=await handler(new Request('https://isolated.invalid/order-portal',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body)}));const data=await r.json();assert.equal(r.status,expected,JSON.stringify(data));return data;}
 return {call,owner,staff,session,members,users,sessions,calls,setup,setupToken,catalogDb,deletion};
}
test('username login normalizes case, returns tokens without email and rejects invalid passwords',async()=>{const f=await fixture();const r=await f.call({action:'admin_login',username:' ADMIN ',password:'initial-pass-1234'});assert.ok(r.access_token);assert.equal(r.user,undefined);assert.equal(r.email,undefined);await f.call({action:'admin_login',username:'admin',password:'wrong'},null,401);await f.call({action:'admin_login',username:'missing',password:'wrong'},null,401);await f.call({action:'admin_login',username:'admin&role=owner',password:'initial-pass-1234'},null,401);});
test('owner creates staff without real email and caller cannot assign owner role',async()=>{const f=await fixture(),token=f.session(f.owner);await f.call({action:'add_admin',username:'Nova.Pessoa',password:'secret-for-staff-123',role:'owner'},token);const m=f.members.find(x=>x.username==='nova.pessoa');assert.equal(m.role,'admin');assert.ok(m.email.endsWith('@accounts.yogomarcas.invalid'));const creation=f.calls.find(x=>x.path==='/auth/v1/admin/users');assert.equal(creation.body.email_confirm,true);assert.equal(creation.body.password,'secret-for-staff-123');assert.ok(!f.calls.some(x=>/invite|recover|otp/.test(x.path)));await f.call({action:'add_admin',username:'NOVA.PESSOA',password:'another-password'},token,409);});
test('team cannot create, reset or disable peers; unauthenticated caller rejected',async()=>{const f=await fixture(),token=f.session(f.staff);for(const action of ['add_admin','reset_admin_password','remove_admin'])await f.call({action,username:'intruder',user_id:f.owner.user_id,password:'secret-for-staff-123'},token,403);await f.call({action:'admin_data'},null,401);await f.call({action:'remove_admin',user_id:f.owner.user_id},f.session(f.owner),403);});
test('disabled membership and revoked session immediately block administrative APIs',async()=>{const f=await fixture(),token=f.session(f.staff);await f.call({action:'remove_admin',user_id:f.staff.user_id},f.session(f.owner));await f.call({action:'admin_data'},token,401);await f.call({action:'admin_login',username:'equipe',password:'initial-pass-1234'},null,401);const ownerToken=f.session(f.owner);f.sessions.splice(f.sessions.findIndex(x=>x.token===ownerToken),1);await f.call({action:'admin_data'},ownerToken,401);});
test('reset revokes old sessions, reactivates staff and accepts only the new password',async()=>{const f=await fixture(),token=f.session(f.staff);f.staff.active=false;await f.call({action:'reset_admin_password',user_id:f.staff.user_id,password:'new-password-12345'},f.session(f.owner));assert.equal(f.staff.active,true);await f.call({action:'admin_data'},token,401);await f.call({action:'admin_login',username:'equipe',password:'initial-pass-1234'},null,401);const r=await f.call({action:'admin_login',username:'equipe',password:'new-password-12345'});assert.ok(r.access_token);});
test('temporary owner password gates mutations until current password is verified and changed',async()=>{const f=await fixture();f.owner.must_change_password=true;const token=f.session(f.owner);await f.call({action:'add_admin',username:'new',password:'new-password-12345'},token,403);const view=await f.call({action:'admin_data'},token);assert.equal(view.me.must_change_password,true);assert.equal(view.me.email,undefined);assert.ok(view.admins.every(x=>!x.email));await f.call({action:'change_password',current_password:'wrong',password:'new-password-12345'},token,401);await f.call({action:'change_password',current_password:'initial-pass-1234',password:'new-password-12345'},token);assert.equal(f.owner.must_change_password,false);await f.call({action:'admin_data'},token,401);});
test('owner setup is single-use, refuses expired token and never sends email',async()=>{const f=await fixture();f.members.length=0;f.setup.expires_at='2000-01-01T00:00:00Z';const body={action:'setup',setup_token:f.setupToken,password:'initial-owner-123'};await f.call(body,null,403);f.setup.expires_at='2099-01-01T00:00:00Z';await f.call(body);assert.equal(f.members.length,1);assert.equal(f.members[0].username,'admin');assert.equal(f.members[0].must_change_password,true);await f.call(body,null,403);});

test('catalog deletion is authenticated, validates identities and uses one atomic RPC',async()=>{const f=await fixture(),id=randomUUID(),parent=randomUUID();await f.call({action:'delete_product',id},null,401);const token=f.session(f.staff);await f.call({action:'delete_flavor',id,product_id:'bad'},token,400);await f.call({action:'delete_product',id:'bad'},token,400);await f.call({action:'delete_flavor',id,product_id:parent},token);const rpc=f.calls.find(x=>x.path==='/rest/v1/rpc/yp_delete_catalog_item');assert.deepEqual(rpc.body,{p_kind:'flavor',p_id:id,p_product:parent});f.deletion.deleted=false;await f.call({action:'delete_product',id},token,409);f.staff.active=false;await f.call({action:'delete_product',id},token,401);});
test('deleted catalog entries are absent from admin data and cannot be revived by stale forms',async()=>{const f=await fixture(),p={id:randomUUID(),line_id:randomUUID(),name:'Deleted',sku:'DEL',package_price:1000,bundle_price:5000,bundle_units:5,package_weight_grams:null,active:false,available:false,has_flavors:true,deleted_at:'2026-01-01',yield_grams:null,yield_min_grams:null};f.catalogDb.yp_products.push(p);const token=f.session(f.owner),view=await f.call({action:'admin_data'},token);assert.equal(view.products.length,0);await f.call({action:'save_product',product:{...p,active:true,available:true}},token,409);assert.equal(p.active,false);await f.call({action:'save_flavor',flavor:{product_id:p.id,name:'Blocked',sku:'BLOCKED',package_price:1000,package_weight_grams:null}},token,409);});

test('admin can disable and enable bundles; omitted fields preserve the existing choice',async()=>{const f=await fixture(),p={id:randomUUID(),line_id:randomUUID(),name:'Produto',sku:'TEST',package_price:1000,bundle_price:5000,bundle_units:5,package_weight_grams:null,active:true,available:true,has_flavors:false,deleted_at:null,yield_grams:null,yield_min_grams:null};f.catalogDb.yp_products.push(p);const token=f.session(f.staff);await f.call({action:'save_product',product:{...p,bundle_enabled:false}},token);assert.equal(p.bundle_enabled,false);const legacy={...p};delete legacy.bundle_enabled;await f.call({action:'save_product',product:legacy},token);assert.equal(p.bundle_enabled,false);await f.call({action:'save_product',product:{...p,bundle_enabled:true}},token);assert.equal(p.bundle_enabled,true);assert.equal(p.bundle_price,5000);assert.equal(p.bundle_units,5);for(const value of ['false',null,0])await f.call({action:'save_product',product:{...p,bundle_enabled:value}},token,400);assert.equal(p.bundle_enabled,true);await f.call({action:'save_product',product:{...p,bundle_enabled:false}},null,401);assert.equal(p.bundle_enabled,true);});
