const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const retention={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'../lib/retention.ts'),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{exports:retention.exports});
const mod={exports:{}};
vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'../lib/portal.ts'),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{exports:mod.exports,require:name=>name==='./retention'?retention.exports:{}});
const {resolveCart,cartKey,startingPrice,normalizeSearch}=mod.exports;
const catalog=()=>({products:[{id:'line',has_flavors:true,active:true,available:true,package_price:1,bundle_price:1,bundle_units:6,yield_grams:6000}],flavors:[{id:'a',product_id:'line',name:'Açaí',active:true,available:true,package_price:5836,bundle_price:35016},{id:'b',product_id:'line',name:'Chocolate',active:true,available:true,package_price:6260,bundle_price:null}],settings:{upsell_enabled:false}});
test('two flavors stay separate and use each flavor price, never parent fallback',()=>{const c=catalog(),items=[{product_id:'line',flavor_id:'a',mode:'package',quantity:2},{product_id:'line',flavor_id:'b',mode:'package',quantity:3}];assert.notEqual(cartKey(items[0]),cartKey(items[1]));const result=resolveCart(items,c);assert.equal(result.length,2);assert.equal(result.reduce((sum,i)=>sum+i.unit_price*i.quantity,0),30452);assert.equal(startingPrice(c.products[0],c.flavors),5836);});
test('missing legacy flavor and mismatched flavor excluded instead of guessed',()=>{const c=catalog();assert.equal(resolveCart([{product_id:'line',mode:'package',quantity:1}],c).length,0);c.flavors[0].product_id='other';assert.equal(resolveCart([{product_id:'line',flavor_id:'a',mode:'package',quantity:1}],c).length,0);});
test('bundle always derives five packages from variant price',()=>{const c=catalog(),r=resolveCart([{product_id:'line',flavor_id:'a',mode:'bundle',quantity:2},{product_id:'line',flavor_id:'b',mode:'bundle',quantity:1}],c);assert.equal(r[0].unit_price,29180);assert.equal(r[0].units,10);assert.equal(r[1].unit_price,31300);});
test('stale upsell with wrong flavor, quantity or excessive price is invalid',()=>{const c=catalog(),regular={product_id:'line',flavor_id:'b',mode:'package',quantity:1},i={product_id:'line',flavor_id:'a',mode:'package',quantity:1,upsell:true};Object.assign(c.settings,{upsell_enabled:true,upsell_product_id:'line',upsell_flavor_id:'b',upsell_price:5000});assert.equal(resolveCart([i,regular],c)[0].unit_price,0);c.settings.upsell_flavor_id='a';assert.equal(resolveCart([i,regular],c)[0].unit_price,5000);assert.equal(resolveCart([{...i,quantity:2},regular],c)[0].unit_price,0);c.settings.upsell_price=9000;assert.equal(resolveCart([i,regular],c)[0].unit_price,0);});
test('flavor search ignores accents',()=>{assert.equal(normalizeSearch('AÇAÍ'),normalizeSearch('acai'));});

test('two counters produce one visual row, correct cost and package equivalent',()=>{const c=catalog(),item={product_id:'line',flavor_id:'a'};let cart=mod.exports.setVariantQuantity([],item,'bundle',1);cart=mod.exports.setVariantQuantity(cart,item,'package',1);const g=mod.exports.groupCart(resolveCart(cart,c));assert.equal(g.length,1);assert.equal(g[0].total,35016);assert.equal(g[0].units,6);cart=mod.exports.setVariantQuantity(cart,item,'bundle',2);cart=mod.exports.setVariantQuantity(cart,item,'package',3);const r=mod.exports.groupCart(resolveCart(cart,c))[0];assert.equal(r.total,75868);assert.equal(r.units,13);cart=mod.exports.setVariantQuantity(cart,item,'bundle',0);assert.equal(cart.length,1);assert.equal(cart[0].quantity,3);assert.equal(cart[0].mode,'package');});
test('changing a regular counter removes the flavor discount across presentations',()=>{const i={product_id:'line',flavor_id:'a',mode:'package',quantity:1,upsell:true,upsell_rule_id:'old'};const next=mod.exports.setVariantQuantity([i],i,'bundle',1);assert.equal(next.length,2);assert.ok(next.every(x=>!x.upsell));assert.ok(next.every(x=>!x.upsell_rule_id));assert.equal(i.upsell,true);});
test('invalid counters and oversized cart rejected without partial mutation',()=>{for(const q of [-1,1.5,1000,Infinity,NaN])assert.throws(()=>mod.exports.setVariantQuantity([],{product_id:'line'},'package',q));const cart=Array.from({length:200},(_,i)=>({product_id:String(i),mode:'package',quantity:1}));assert.throws(()=>mod.exports.setVariantQuantity(cart,{product_id:'extra'},'package',1));assert.equal(cart.length,200);});
