// Exercises the real Edge handler with isolated, in-memory HTTP dependencies.
// This file makes no network calls and never changes a live catalog or order.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {webcrypto:crypto,randomUUID}=require('node:crypto');
const transpile=source=>ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText;
const projectionModule={exports:{}};vm.runInNewContext(transpile(fs.readFileSync(path.join(__dirname,'../lib/projection.ts'),'utf8')),{exports:projectionModule.exports});
const retentionModule={exports:{}};vm.runInNewContext(transpile(fs.readFileSync(path.join(__dirname,'../lib/retention.ts'),'utf8')),{exports:retentionModule.exports});
const sha=async value=>Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))).toString('hex');
async function fixture(){
 const first={id:randomUUID(),phone:'5545999999999',store_name:'Loja de teste A',contact_name:'Teste',portions:[{id:'small_cone',name:'Casquinha pequena',grams:100,price:500}],preferred_portion_id:'small_cone',updated_at:'2026-09-04T00:00:00.000+00:00'};
 const second={...first,id:randomUUID(),phone:'5545999999998',store_name:'Loja de teste B'};
 const tokenA='a'.repeat(64),tokenB='b'.repeat(64),line={id:randomUUID(),active:true};
 const base={id:randomUUID(),line_id:line.id,deleted_at:null,name:'Base',sku:'TEST-BASE',package_label:'Pacote',package_price:5000,bundle_price:25000,bundle_units:5,yield_grams:6000,yield_min_grams:5500,active:true,available:true};
 const support={...base,id:randomUUID(),name:'Lubrificante',sku:'TEST-LUB',package_price:3000,bundle_price:null,bundle_units:null,yield_grams:null,yield_min_grams:null};
 const settings={id:1,whatsapp:'554532541200',ordering_enabled:true,minimum_order:0,upsell_enabled:false};
 const db={yp_customers:[first,second],yp_customer_devices:[{token_hash:await sha(tokenA),customer_id:first.id,revoked_at:null},{token_hash:await sha(tokenB),customer_id:second.id,revoked_at:null}],yp_lines:[line],yp_products:[base,support],yp_flavors:[],yp_settings:[settings],yp_orders:[],yp_upsell_rules:[],yp_customer_carts:[],yp_customer_favorites:[]};
 let handler;
 const fakeFetch=async (url,init={})=>{const u=new URL(url);assert.equal(u.origin,'https://isolated.invalid');if(u.pathname==='/rest/v1/rpc/yp_check_rate')return Response.json(true);if(u.pathname==='/rest/v1/rpc/yp_save_customer_cart'){const b=JSON.parse(init.body),cart={customer_id:b.p_customer,revision:b.p_revision+1,items:b.p_items,total:b.p_total,status:'active'};db.yp_customer_carts.push(cart);return Response.json(cart);}const table=u.pathname.split('/').pop();assert.ok(db[table],table);let rows=db[table].filter(row=>[...u.searchParams].every(([key,v])=>!v.startsWith('eq.')&&!v.startsWith('is.')||v.startsWith('eq.')?(!v.startsWith('eq.')||String(row[key])===v.slice(3)):row[key]===null));if(init.method==='POST'){const value=JSON.parse(init.body);if(table==='yp_orders'){value.is_test=false;value.created_at=new Date().toISOString();}db[table].push(value);return Response.json([value]);}if(init.method==='PATCH'){rows.forEach(r=>Object.assign(r,JSON.parse(init.body)));}
  const order=u.searchParams.get('order');if(order)rows.sort((a,b)=>{for(const field of order.split(',')){const [key,direction]=field.split('.');const n=typeof a[key]==='number'&&typeof b[key]==='number'?a[key]-b[key]:String(a[key]??'').localeCompare(String(b[key]??''));if(n)return direction==='desc'?-n:n;}return 0;});
  if(u.searchParams.has('limit')){const offset=Number(u.searchParams.get('offset')||0);rows=rows.slice(offset,offset+Number(u.searchParams.get('limit')));}
  return Response.json(rows);};
 const source=fs.readFileSync(path.join(__dirname,'../supabase/functions/order-portal/index.ts'),'utf8').replace("import {calculateProjection} from '../../../lib/projection.ts';",'').replace("import {BUNDLE_UNITS,bundlePrice,orderMessage,cartOffers,matchesOffer} from '../../../lib/retention.ts';",'');
 vm.runInNewContext(transpile(source),{Deno:{env:{get:name=>name==='SUPABASE_URL'?'https://isolated.invalid':'isolated-only'},serve:fn=>handler=fn},calculateProjection:projectionModule.exports.calculateProjection,...retentionModule.exports,crypto,TextEncoder,TextDecoder,Uint8Array,Response,Request,URL,fetch:fakeFetch});
 const payload={id:randomUUID(),client_token:randomUUID(),session_id:randomUUID(),customer_device_token:tokenA,profile_version:first.updated_at,portion_id:'small_cone',customer:{name:'Pessoa de teste',company:'FORGED',phone:'FORGED',city:'Toledo',state:'PR'},items:[{product_id:base.id,mode:'bundle',quantity:2,unit_price:25000},{product_id:support.id,mode:'package',quantity:1,unit_price:3000}],projection_snapshot:{revenue_max:999999999}};
 async function call(data,expected=200){const r=await handler(new Request('https://isolated.invalid/functions/v1/order-portal',{method:'POST',body:JSON.stringify({action:'order',...data}),headers:{'Content-Type':'application/json'}}));const result=await r.json();assert.equal(r.status,expected,JSON.stringify(result));return result;}
 return {db,call,payload,first,second,tokenA,tokenB,base,support,settings,catalog:async(version)=>{const r=await handler(new Request('https://isolated.invalid/functions/v1/order-portal'+(version?'?offers='+version:'')));assert.equal(r.status,200);return r.json();}};
}
test('handler records canonical shop, base yield, bundle units and isolated snapshot',async()=>{const f=await fixture(),result=await f.call(f.payload),o=f.db.yp_orders[0];assert.equal(result.total,53000);assert.equal(o.company,f.first.store_name);assert.equal(o.phone,f.first.phone);assert.equal(o.customer_id,f.first.id);assert.deepEqual([o.projection_snapshot.packets,o.projection_snapshot.servings_min,o.projection_snapshot.servings_max,o.projection_snapshot.base_cost,o.projection_snapshot.excluded_cost],[10,550,600,50000,3000]);assert.equal(o.projection_snapshot.revenue_max,300000);assert.equal(o.projection_snapshot.surplus_min,225000);assert.ok(result.whatsapp_url.startsWith('https://wa.me/554532541200?text='));assert.ok(!result.message.includes('FORGED'));});
test('same-shop retry is idempotent and other shop cannot access it',async()=>{const f=await fixture(),a=await f.call(f.payload),b=await f.call(f.payload);assert.equal(a.id,b.id);assert.equal(f.db.yp_orders.length,1);await f.call({...f.payload,customer_device_token:f.tokenB},403);});
test('revoked device cannot retrieve an existing order',async()=>{const f=await fixture();await f.call(f.payload);f.db.yp_customer_devices[0].revoked_at=new Date().toISOString();await f.call(f.payload,401);});
test('stale profile and changed price rejected with no order',async()=>{const f=await fixture();await f.call({...f.payload,profile_version:'stale'},409);await f.call({...f.payload,items:[{...f.payload.items[0],unit_price:1}]},409);assert.equal(f.db.yp_orders.length,0);});
test('support-only order has no invented production estimate',async()=>{const f=await fixture();await f.call({...f.payload,items:[f.payload.items[1]]});assert.equal(f.db.yp_orders[0].projection_snapshot,null);});
test('saved snapshot remains historical after retail price changes',async()=>{const f=await fixture();await f.call(f.payload);f.first.portions[0].price=1000;f.first.updated_at='2026-09-05T00:00:00.000+00:00';await f.call(f.payload);assert.equal(f.db.yp_orders[0].projection_snapshot.revenue_max,300000);await f.call({...f.payload,id:randomUUID(),profile_version:f.first.updated_at});assert.equal(f.db.yp_orders[1].projection_snapshot.revenue_max,600000);});
test('paused ordering stays blocked',async()=>{const f=await fixture();f.settings.ordering_enabled=false;await f.call(f.payload,409);assert.equal(f.db.yp_orders.length,0);});

function flavored(f){f.base.has_flavors=true;f.base.package_price=null;const a={id:randomUUID(),product_id:f.base.id,deleted_at:null,name:'Baunilha',sku:'EI-001',package_price:5836,bundle_price:29180,package_weight_grams:1850,active:true,available:true},b={...a,id:randomUUID(),name:'Chocolate suíço',sku:'EI-002',package_price:6260,bundle_price:31300};f.db.yp_flavors.push(a,b);return [a,b];}
const packet=(f,v,quantity=1)=>({product_id:f.base.id,flavor_id:v.id,mode:'package',quantity,unit_price:v.package_price});
test('two flavors in the same line preserve independent quantities, price, weight and WhatsApp codes',async()=>{const f=await fixture(),[a,b]=flavored(f);const r=await f.call({...f.payload,items:[packet(f,a,2),packet(f,b,3)]});assert.equal(r.total,30452);assert.equal(f.db.yp_orders[0].items.length,2);assert.equal(f.db.yp_orders[0].items[0].flavor_id,a.id);assert.equal(f.db.yp_orders[0].items[0].package_weight_grams,1850);assert.ok(r.message.includes('EI-001 — 2 pacotes'));assert.ok(r.message.includes('EI-002 — 3 pacotes'));assert.equal(f.db.yp_orders[0].projection_snapshot.packets,5);});
test('missing, foreign, inactive and unavailable flavors are rejected without orders',async()=>{const f=await fixture(),[a,b]=flavored(f);await f.call({...f.payload,items:[{...packet(f,a),flavor_id:null}]},409);await f.call({...f.payload,items:[{...packet(f,a),product_id:f.support.id}]},409);a.available=false;await f.call({...f.payload,items:[packet(f,a)]},409);b.active=false;await f.call({...f.payload,items:[packet(f,b)]},409);assert.equal(f.db.yp_orders.length,0);});
test('duplicate flavor rejected, different presentations of same flavor accepted',async()=>{const f=await fixture(),[a]=flavored(f);await f.call({...f.payload,items:[packet(f,a),packet(f,a)]},400);const r=await f.call({...f.payload,items:[packet(f,a),{...packet(f,a),mode:'bundle',unit_price:29180}]});assert.equal(r.total,35016);assert.equal(f.db.yp_orders[0].projection_snapshot.packets,6);});
test('variant bundle ignores stale bundle fields and uses five times package price',async()=>{const f=await fixture(),[a]=flavored(f);const item={...packet(f,a),mode:'bundle',unit_price:29180};f.base.bundle_units=null;a.bundle_price=null;await f.call({...f.payload,items:[item]});assert.equal(f.db.yp_orders[0].items[0].units,5);assert.equal(f.db.yp_orders[0].items[0].line_total,29180);});
test('forged price and malformed flavor IDs rejected',async()=>{const f=await fixture(),[a]=flavored(f);await f.call({...f.payload,items:[{...packet(f,a),unit_price:1}]},409);await f.call({...f.payload,items:[{...packet(f,a),flavor_id:'malformed'}]},400);});
test('upsell is bound to one specific flavor and canonical discounted price',async()=>{const f=await fixture(),[a,b]=flavored(f);Object.assign(f.settings,{upsell_enabled:true,upsell_product_id:f.base.id,upsell_flavor_id:b.id,upsell_price:6000});const offer={...packet(f,b),upsell:true,unit_price:6000};await f.call({...f.payload,items:[packet(f,a),{...offer,flavor_id:a.id}]},400);await f.call({...f.payload,items:[packet(f,a),{...offer,quantity:0}]},400);const result=await f.call({...f.payload,items:[packet(f,a),offer]});assert.equal(result.total,11836);assert.equal(f.db.yp_orders[0].items[1].upsell,true);});
test('flavor snapshot survives later catalog rename and price change',async()=>{const f=await fixture(),[a]=flavored(f),body={...f.payload,items:[packet(f,a)]};await f.call(body);a.name='Renomeado';a.package_price=9999;await f.call(body);assert.equal(f.db.yp_orders.length,1);assert.equal(f.db.yp_orders[0].items[0].flavor_name,'Baunilha');assert.equal(f.db.yp_orders[0].items[0].unit_price,5836);});

// Customer data is scoped by the verified device, regardless of caller-supplied IDs.
test('history never exposes another shop or administrative secrets',async()=>{const f=await fixture();await f.call(f.payload);Object.assign(f.db.yp_orders[0],{status_note:'private team note',status:'confirmed'});const r=await f.call({action:'customer_history',device_token:f.tokenB,customer_id:f.first.id});assert.equal(r.orders.length,0);const own=await f.call({action:'customer_history',device_token:f.tokenA});assert.equal(own.orders.length,1);assert.equal(own.orders[0].client_token_hash,undefined);assert.equal(own.orders[0].status_note,undefined);assert.equal(own.orders[0].session_id,undefined);});
test('favorites and draft reads are scoped to the signed-in shop',async()=>{const f=await fixture();f.db.yp_customer_favorites.push({customer_id:f.first.id,flavor_id:f.base.id});f.db.yp_customer_carts.push({customer_id:f.first.id,revision:1,status:'active',items:[f.payload.items[0]],total:25000});const favorites=await f.call({action:'customer_favorites',device_token:f.tokenB,customer_id:f.first.id});assert.equal(favorites.flavor_ids.length,0);const draft=await f.call({action:'customer_cart',device_token:f.tokenB,customer_id:f.first.id});assert.equal(draft.cart,null);});
test('customer shopping endpoints reject missing or revoked devices',async()=>{const f=await fixture();for(const action of ['customer_history','customer_favorites','customer_cart','customer_cart_save'])await f.call({action},401);f.db.yp_customer_devices[0].revoked_at='now';await f.call({action:'customer_history',device_token:f.tokenA},401);});
test('contextual offer requires its trigger and canonical price',async()=>{const f=await fixture();const r={id:randomUUID(),trigger_product_id:f.base.id,product_id:f.support.id,flavor_id:null,price:2500,priority:0,active:true,title:'Complemento'};f.db.yp_upsell_rules.push(r);f.settings.contextual_upsell_enabled=true;const suggestion={...f.payload.items[1],upsell:true,upsell_rule_id:r.id,unit_price:2500};await f.call({...f.payload,items:[suggestion]},409);await f.call({...f.payload,items:[f.payload.items[0],{...suggestion,unit_price:1}]},409);await f.call({...f.payload,items:[f.payload.items[0],{...suggestion,upsell_rule_id:randomUUID()}]},409);const result=await f.call({...f.payload,items:[f.payload.items[0],suggestion]});assert.equal(result.total,52500);assert.equal(f.db.yp_orders[0].items[1].upsell_rule_id,r.id);});

test('WhatsApp combines presentations and snapshots codes against edits and tampering',async()=>{const f=await fixture(),[a]=flavored(f);const body={...f.payload,items:[{...packet(f,a,3),internal_code:'FORGED'},{...packet(f,a,2),mode:'bundle',unit_price:29180,bundle_units:100,internal_code:'FORGED'}]};const r=await f.call(body);assert.equal(r.total,75868);assert.ok(r.message.includes('EI-001 — 13 pacotes'));assert.equal((r.message.match(/EI-001/g)||[]).length,1);assert.ok(!r.message.includes('fardo'));assert.ok(!r.message.includes('FORGED'));assert.ok(!r.message.includes('Baunilha'));a.sku='NEW-CODE';a.package_price=10000;const retry=await f.call(body);assert.equal(retry.message,r.message);assert.equal(f.db.yp_orders[0].projection_snapshot.packets,13);});

test('deleted catalog records cannot be quoted but existing orders remain readable',async()=>{const f=await fixture(),[a]=flavored(f),body={...f.payload,items:[packet(f,a)]};const saved=await f.call(body);a.deleted_at='2026-01-01';a.active=false;await f.call({...body,id:randomUUID()},409);assert.equal((await f.call(body)).message,saved.message);f.base.deleted_at='2026-01-01';f.base.active=false;await f.call({...body,id:randomUUID()},409);assert.equal(f.db.yp_orders.length,1);});

test('bundle-disabled simple product rejects new bundles and accepts packages',async()=>{const f=await fixture();f.base.bundle_enabled=false;await f.call(f.payload,409);assert.equal(f.db.yp_orders.length,0);const result=await f.call({...f.payload,items:[{...f.payload.items[0],mode:'package',quantity:10,unit_price:5000}]});assert.equal(result.total,50000);assert.equal(f.db.yp_orders[0].items[0].units,10);});
test('all flavors inherit disabled bundle purchases without disabling package orders',async()=>{const f=await fixture(),flavors=flavored(f);f.base.bundle_enabled=false;for(const flavor of flavors)await f.call({...f.payload,items:[{...packet(f,flavor),mode:'bundle',unit_price:flavor.package_price*5}]},409);assert.equal(f.db.yp_orders.length,0);const result=await f.call({...f.payload,items:flavors.map(flavor=>packet(f,flavor))});assert.equal(result.total,12096);});
test('disabling bundles preserves existing order receipts and idempotency',async()=>{const f=await fixture(),saved=await f.call(f.payload);f.base.bundle_enabled=false;const again=await f.call(f.payload);assert.equal(again.id,saved.id);assert.equal(again.message,saved.message);assert.equal(again.total,saved.total);assert.equal(f.db.yp_orders.length,1);await f.call({...f.payload,id:randomUUID()},409);});
test('draft synchronization rejects disabled bundles before saving and accepts packages',async()=>{for(const withFlavors of [false,true]){const f=await fixture(),flavor=withFlavors?flavored(f)[0]:null;f.base.bundle_enabled=false;const item=flavor?packet(f,flavor):{product_id:f.base.id,mode:'package',quantity:1,unit_price:5000};const body={action:'customer_cart_save',device_token:f.tokenA,revision:0,items:[{...item,mode:'bundle'}]};await f.call(body,409);assert.equal(f.db.yp_customer_carts.length,0);await f.call({...body,items:[item]});assert.equal(f.db.yp_customer_carts.length,1);assert.equal(f.db.yp_customer_carts[0].items[0].mode,'package');assert.equal(f.db.yp_customer_carts[0].total,item.unit_price);}});
test('public catalog exposes the product choice and masks disabled flavor bundle prices',async()=>{const f=await fixture(),[a]=flavored(f);f.base.bundle_enabled=false;const result=await f.catalog();const p=result.products.find(p=>p.id===f.base.id);assert.equal(p.bundle_enabled,false);assert.equal(p.bundle_price,null);assert.equal(p.bundle_units,null);assert.equal(result.flavors.find(x=>x.id===a.id).bundle_price,null);});

test('flavor-specific rules are returned only to clients supporting the new offer protocol',async()=>{const f=await fixture(),[a,b]=flavored(f);f.db.yp_upsell_rules.push({id:randomUUID(),trigger_product_id:f.base.id,trigger_flavor_id:b.id,product_id:f.base.id,flavor_id:a.id,price:null,priority:0,active:true});assert.equal((await f.catalog()).upsell_rules.length,0);assert.equal((await f.catalog('2')).upsell_rules[0].trigger_flavor_id,b.id);});
test('authenticated order flow accepts a flavor upsell in packages and bundles together',async()=>{const f=await fixture(),[a,b]=flavored(f);Object.assign(f.settings,{upsell_enabled:true,upsell_product_id:f.base.id,upsell_flavor_id:b.id,upsell_price:6000});const offer={...packet(f,b,3),upsell:true,unit_price:6000};const r=await f.call({...f.payload,items:[packet(f,a),offer,{...offer,mode:'bundle',quantity:2,unit_price:30000}]});assert.equal(r.total,83836);assert.ok(r.message.includes('EI-002 — 13 pacotes'));assert.equal(f.db.yp_orders[0].projection_snapshot.packets,14);});


test('checkout defaults come from the latest real order of the authenticated shop only',async()=>{
 const f=await fixture();f.first.pin_hash='private-hash';f.first.pin_salt='private-salt';
 f.db.yp_orders.push(
  {id:randomUUID(),customer_id:f.first.id,is_test:false,customer_name:'Antigo',city:'Toledo',state:'PR',created_at:'2026-09-01T00:00:00Z'},
  {id:randomUUID(),customer_id:f.first.id,is_test:false,customer_name:'Atual',city:'Joinville',state:'SC',created_at:'2026-09-02T00:00:00Z'},
  {id:randomUUID(),customer_id:f.first.id,is_test:true,customer_name:'Teste excluído',city:'Cuiabá',state:'MT',created_at:'2026-09-03T00:00:00Z'},
  {id:randomUUID(),customer_id:f.second.id,is_test:false,customer_name:'Outra loja',city:'Curitiba',state:'PR',created_at:'2026-09-04T00:00:00Z'}
 );
 const result=await f.call({action:'customer_restore',device_token:f.tokenA,customer_id:f.second.id,phone:f.second.phone});
 assert.deepEqual(result.profile.checkout_details,{order_id:f.db.yp_orders[1].id,name:'Atual',city:'Joinville',state:'SC'});
 assert.equal(result.profile.pin_hash,undefined);assert.equal(result.profile.pin_salt,undefined);
 const other=await f.call({action:'customer_restore',device_token:f.tokenB});assert.equal(other.profile.checkout_details.name,'Outra loja');
});

test('preparing a new order saves changed checkout defaults without rewriting the previous order',async()=>{
 const f=await fixture();
 const initial=await f.call({action:'customer_restore',device_token:f.tokenA});assert.equal(initial.profile.checkout_details,null);
 await f.call(f.payload);f.db.yp_orders[0].created_at='2026-01-01T00:00:00Z';
 let result=await f.call({action:'customer_restore',device_token:f.tokenA});assert.equal(result.profile.checkout_details.name,'Pessoa de teste');assert.equal(result.profile.checkout_details.city,'Toledo');
 const next={...f.payload,id:randomUUID(),client_token:randomUUID(),customer:{...f.payload.customer,name:'Novo nome',city:'Blumenau',state:'SC'}};
 await f.call(next);result=await f.call({action:'customer_restore',device_token:f.tokenA});
 assert.deepEqual(result.profile.checkout_details,{order_id:next.id,name:'Novo nome',city:'Blumenau',state:'SC'});
 assert.equal(f.db.yp_orders[0].city,'Toledo');assert.equal(f.db.yp_orders[0].customer_name,'Pessoa de teste');
});

test('checkout defaults require a valid remembered device and survive editing shop settings',async()=>{
 const f=await fixture();await f.call(f.payload);
 await f.call({action:'customer_restore',phone:f.first.phone},401);
 const updated=await f.call({action:'customer_update',device_token:f.tokenA,store_name:'Loja editada',contact_name:'Outro contato',portions:f.first.portions,preferred_portion_id:f.first.preferred_portion_id});
 assert.equal(updated.profile.checkout_details.city,'Toledo');assert.equal(updated.profile.checkout_details.state,'PR');
 f.db.yp_customer_devices[0].revoked_at=new Date().toISOString();await f.call({action:'customer_restore',device_token:f.tokenA},401);
});
