const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/retention.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{exports:m.exports});
const {cartOffer,repeatOrder,mergeRepeat,matchesOffer}=m.exports;
function catalog(){return {products:[{id:'flavorings',active:true,available:true,has_flavors:true},{id:'base',active:true,available:true,package_price:5016,bundle_price:30096,bundle_units:6}],flavors:[{id:'vanilla',product_id:'flavorings',active:true,available:true,package_price:2080}],settings:{contextual_upsell_enabled:true,upsell_enabled:false},upsell_rules:[{id:'rule',trigger_product_id:'flavorings',product_id:'base',flavor_id:null,active:true,priority:0,price:null,title:'Base'}]};}
const trigger={product_id:'flavorings',flavor_id:'vanilla',mode:'package',quantity:1};
test('one contextual suggestion, suppressed when complement already exists in any presentation',()=>{const c=catalog();assert.equal(cartOffer(c,[trigger]).price,5016);assert.equal(cartOffer(c,[]),null);assert.equal(cartOffer(c,[trigger,{product_id:'base',mode:'bundle',quantity:1}]),null);c.products[1].available=false;assert.equal(cartOffer(c,[trigger]),null);});
test('rules prioritize only eligible targets and fall back to the general suggestion',()=>{const c=catalog();c.upsell_rules[0].price=9000;assert.equal(cartOffer(c,[trigger]),null);Object.assign(c.settings,{upsell_enabled:true,upsell_product_id:'base',upsell_title:'Geral',upsell_price:4900});assert.equal(cartOffer(c,[trigger]).rule_id,null);c.upsell_rules[0].price=4800;assert.equal(cartOffer(c,[trigger]).rule_id,'rule');c.settings.contextual_upsell_enabled=false;assert.equal(cartOffer(c,[trigger]).price,4900);});
test('repeat reprices units and bundles, reports unavailable items, drops old discounts',()=>{const c=catalog();const r=repeatOrder([{product_id:'base',name:'Base',mode:'bundle',quantity:2,bundle_units:5,unit_price:25000,upsell:true},{product_id:'gone',name:'Removido',mode:'package',quantity:1,unit_price:99}],c);assert.equal(r.cart.length,1);assert.equal(r.cart[0].upsell,false);assert.equal(r.cart[0].quantity,2);assert.equal(r.changed[0],'Base');assert.equal(r.unavailable[0],'Removido');assert.equal(r.cart[0].upsell_rule_id,undefined);});
test('repeat merge preserves the existing cart and prevents quantity overflow',()=>{const current=[{...trigger,quantity:2}];const merged=mergeRepeat(current,[{...trigger,quantity:3},{product_id:'base',mode:'package',quantity:1}]);assert.equal(merged.length,2);assert.equal(merged[0].quantity,5);assert.equal(current[0].quantity,2);assert.throws(()=>mergeRepeat(current,[{...trigger,quantity:999}]),/999/);});
test('a contextual discount cannot be used with a different rule, flavor, or quantity',()=>{const offer=cartOffer(catalog(),[trigger]);const i={product_id:'base',flavor_id:null,mode:'package',quantity:1,upsell:true,upsell_rule_id:'rule'};assert.equal(matchesOffer(i,offer),true);for(const change of [{upsell_rule_id:null},{quantity:2},{mode:'bundle'},{flavor_id:'vanilla'}])assert.equal(matchesOffer({...i,...change},offer),false);});

test('repeat reports disabled bundles but permits packages from the same product',()=>{const c=catalog();c.products[1].bundle_enabled=false;const r=repeatOrder([{product_id:'base',name:'Base fardo',mode:'bundle',quantity:2,unit_price:25080},{product_id:'base',name:'Base pacote',mode:'package',quantity:3,unit_price:5016}],c);assert.equal(r.cart.length,1);assert.equal(r.cart[0].mode,'package');assert.equal(r.cart[0].quantity,3);assert.equal(r.unavailable[0],'Base fardo');});
test('disabled bundle cannot trigger an offer, package trigger and package complement remain eligible',()=>{const c=catalog();c.products[0].bundle_enabled=false;c.products[1].bundle_enabled=false;assert.equal(cartOffer(c,[{...trigger,mode:'bundle'}]),null);assert.equal(cartOffer(c,[trigger]).product_id,'base');assert.equal(cartOffer(c,[trigger]).price,5016);});
