'use client';
import {useState} from 'react';
import {ArrowLeft,Check,LoaderCircle,Plus,PenLine,Search,Trash2} from 'lucide-react';
import {toast} from 'sonner';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {api,cents,Flavor,money,moneyInput,normalizeSearch,Product} from '@/lib/portal';
import CatalogDeleteDialog,{DeleteTarget} from './catalog-delete-dialog';
export default function AdminFlavors({product,flavors,onClose,onSaved}:{product:Product;flavors:Flavor[];onClose:()=>void;onSaved:()=>Promise<unknown>}){
 const [search,setSearch]=useState(''),[editing,setEditing]=useState<Flavor|null>(null),[price,setPrice]=useState(''),[busy,setBusy]=useState(false),[deleting,setDeleting]=useState<DeleteTarget|null>(null);
 const all=flavors.filter(f=>f.product_id===product.id),list=all.filter(f=>normalizeSearch(`${f.name} ${f.sku}`).includes(normalizeSearch(search)));
 function edit(f:Flavor){setEditing({...f});setPrice(moneyInput(f.package_price));}
 const askDelete=(f:Flavor)=>setDeleting({kind:'flavor',id:f.id,name:f.name,product_id:product.id});
 async function save(e:React.FormEvent){e.preventDefault();if(!editing)return;setBusy(true);try{await api('save_flavor',{flavor:{...editing,package_price:cents(price),bundle_price:cents(price)===null?null:cents(price)!*5}},true);await onSaved();setEditing(null);toast.success('Sabor salvo.');}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 return <><Dialog open onOpenChange={open=>{if(!open&&!busy&&!deleting)onClose();}}><DialogContent className="admin-dialog catalog-editor flavor-admin-dialog sm:max-w-3xl" onEscapeKeyDown={e=>{if(busy)e.preventDefault();}} onPointerDownOutside={e=>{if(busy)e.preventDefault();}}><DialogHeader><div className="editor-kicker">{product.name}</div><DialogTitle>{editing?(editing.id?'Editar sabor':'Novo sabor'):'Gerenciar sabores'}</DialogTitle><DialogDescription>{editing?'Preencha os campos e salve as alterações.':'Encontre um sabor para editar preço, código ou disponibilidade.'}</DialogDescription></DialogHeader>
 {editing?<form className="catalog-editor-form" onSubmit={save}><div className="catalog-editor-scroll"><fieldset className="editor-fields" disabled={busy}><button type="button" className="editor-back" onClick={()=>setEditing(null)}><ArrowLeft size={16}/>Voltar aos sabores</button><section className="editor-section"><div className="editor-section-heading"><h3>Informações do sabor</h3><span>* Obrigatório</span></div><div className="form-grid"><label className="field"><span>Nome do sabor *</span><input required maxLength={120} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} placeholder="Ex.: Chocolate"/></label><label className="field"><span>Código interno *</span><input required maxLength={60} value={editing.sku} onChange={e=>setEditing({...editing,sku:e.target.value.toUpperCase()})} placeholder="Ex.: EI-001"/></label><label className="field"><span>Preço do pacote (R$)</span><input inputMode="decimal" pattern="[0-9]+([.,][0-9]{1,2})?" value={price} onChange={e=>setPrice(e.target.value)} placeholder="0,00"/></label><label className="field"><span>Peso do pacote (g)</span><input type="number" min={1} max={100000} step={1} value={editing.package_weight_grams??''} onChange={e=>setEditing({...editing,package_weight_grams:e.target.value?Number(e.target.value):null})} placeholder="Ex.: 1850"/></label></div><div className="computed-value"><div><span>Fardo de 5 pacotes</span><small>Valor calculado automaticamente</small></div><strong>{cents(price)?money(cents(price)!*5):'Preencha o preço'}</strong></div></section><section className="editor-section"><div className="editor-section-heading"><h3>Disponibilidade</h3></div><label className="toggle-row"><strong>Visível no catálogo</strong><Switch checked={editing.active} onCheckedChange={active=>setEditing({...editing,active})} aria-label="Sabor visível no catálogo"/></label><label className="toggle-row"><strong>Disponível para pedido</strong><Switch checked={editing.available} onCheckedChange={available=>setEditing({...editing,available})} aria-label="Sabor disponível para pedido"/></label><label className="field"><span>Ordem de exibição</span><input type="number" min={0} max={999} step={1} value={editing.position} onChange={e=>setEditing({...editing,position:Number(e.target.value)})}/></label></section></fieldset></div><footer className="editor-footer">{editing.id&&<button type="button" className="btn danger-outline" disabled={busy} onClick={()=>askDelete(editing)}><Trash2 size={16}/>Excluir sabor</button>}<div className="editor-primary-actions"><button type="button" disabled={busy} className="btn secondary" onClick={()=>setEditing(null)}>Cancelar</button><button type="submit" disabled={busy} className="btn primary">{busy?<LoaderCircle size={16} className="spin"/>:<Check size={16}/>}Salvar sabor</button></div></footer></form>:
 <div className="flavor-admin-browser"><div className="flavor-admin-toolbar"><label className="admin-search"><Search size={18}/><input aria-label="Buscar sabor cadastrado" placeholder="Buscar nome ou código" value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="btn primary" onClick={()=>edit({id:'',sku:'',product_id:product.id,name:'',package_weight_grams:null,package_price:null,bundle_price:null,active:true,available:true,position:Math.min(all.length,999)})}><Plus size={16}/>Novo sabor</button></div><div className="flavor-list-count">{list.length} {list.length===1?'sabor':'sabores'}</div><div className="flavor-admin-list">{list.map(f=><div key={f.id} className="flavor-admin-row"><div className="flavor-admin-info"><strong>{f.name}</strong><small><code>{f.sku}</code>{f.package_weight_grams?` · ${f.package_weight_grams.toLocaleString('pt-BR')} g`:''}</small><span className={`status ${!f.active?'cancelled':f.available?'confirmed':'prepared'}`}>{!f.active?'Oculto':f.available?'Disponível':'Indisponível'}</span></div><div className="flavor-admin-value"><strong>{f.package_price?money(f.package_price):'Sem preço'}</strong><small>por pacote</small></div><div className="catalog-row-actions"><button type="button" className="btn secondary" onClick={()=>edit(f)} aria-label={`Editar ${f.name}`}><PenLine size={15}/>Editar</button><button type="button" className="icon-button danger-icon" onClick={()=>askDelete(f)} aria-label={`Excluir sabor ${f.name}`} title="Excluir sabor"><Trash2 size={17}/></button></div></div>)}{!list.length&&<div className="admin-list-empty"><p>{all.length?'Nenhum sabor encontrado.':'Esta linha ainda não tem sabores.'}</p><span>{all.length?'Tente outro nome ou código.':'Clique em Novo sabor para começar.'}</span></div>}</div></div>}
 </DialogContent></Dialog><CatalogDeleteDialog target={deleting} onClose={()=>setDeleting(null)} onDeleted={async()=>{if(editing?.id===deleting?.id)setEditing(null);await onSaved();toast.success('Sabor excluído do catálogo.');}}/></>;
}
