'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {api,logout} from '@/lib/portal';
export type TeamMember={user_id:string;username:string;role:string;active:boolean;must_change_password:boolean};
export function PasswordForm({required=false,onChanged}:{required?:boolean;onChanged:()=>void}){
 const [current,setCurrent]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <form className="admin-panel settings-form password-panel" onSubmit={async e=>{e.preventDefault();if(password!==confirm){setError('As novas senhas precisam ser iguais.');return;}setBusy(true);setError('');try{await api('change_password',{current_password:current,password},true);await logout();setCurrent('');setPassword('');setConfirm('');toast.success('Senha alterada. Entre com a nova senha.');onChanged();}catch(e){setError(e instanceof Error?e.message:'Não foi possível alterar.');}finally{setBusy(false);}}}><h2>{required?'Defina sua senha':'Alterar minha senha'}</h2>{required&&<p>Troque a senha inicial para acessar a administração.</p>}<label className="field"><span>Senha atual</span><input required type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)}/></label><label className="field"><span>Nova senha</span><input required minLength={12} maxLength={72} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="field"><span>Repita a nova senha</span><input required minLength={12} maxLength={72} type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><p className="small muted">Use de 12 a 72 caracteres.</p>{error&&<p className="error-box" role="alert">{error}</p>}<button className="btn primary" disabled={busy}>{busy?'Salvando…':'Salvar nova senha'}</button></form>;
}
export default function AdminTeam({members,onSaved}:{members:TeamMember[];onSaved:()=>Promise<unknown>}){
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[reset,setReset]=useState<TeamMember|null>(null),[busy,setBusy]=useState(false),[remove,setRemove]=useState<TeamMember|null>(null);
 const fail=(e:unknown)=>toast.error(e instanceof Error?e.message:'Não foi possível salvar o acesso.');
 return <div className="settings-layout"><section className="admin-panel"><div className="panel-heading"><div><h2>Acesso da equipe</h2><p>Você cadastra o login e a senha de cada pessoa.</p></div></div>{members.map(a=><div className="admin-member" key={a.user_id}><div><strong>{a.username}</strong><small>{a.role==='owner'?'Responsável':a.active?'Administrador':'Acesso desativado'}</small></div>{a.role!=='owner'&&<div className="button-row"><button disabled={busy} className="btn secondary" onClick={()=>{setReset(a);setPassword('');}}>{a.active?'Redefinir senha':'Reativar acesso'}</button>{a.active&&<button disabled={busy} className="text-button" onClick={()=>setRemove(a)}>Desativar</button>}</div>}</div>)}{remove&&<div className="notice-bar"><div><p>Desativar o acesso de <strong>{remove.username}</strong>?</p><div className="button-row"><button className="btn secondary" disabled={busy} onClick={()=>setRemove(null)}>Cancelar</button><button className="btn primary" disabled={busy} onClick={async()=>{setBusy(true);try{await api('remove_admin',{user_id:remove.user_id},true);await onSaved();setRemove(null);toast.success('Acesso desativado.');}catch(e){fail(e);}finally{setBusy(false);}}}>Desativar acesso</button></div></div></div>}</section><form className="admin-panel settings-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api(reset?'reset_admin_password':'add_admin',reset?{user_id:reset.user_id,password}:{username,password},true);await onSaved();setUsername('');setPassword('');setReset(null);toast.success(reset?'Nova senha salva. Compartilhe com a pessoa.':'Acesso criado. Compartilhe o login e a senha com a pessoa.');}catch(e){fail(e);}finally{setBusy(false);}}}><h2>{reset?`Nova senha · ${reset.username}`:'Adicionar administrador'}</h2>{!reset&&<label className="field"><span>Login</span><input required minLength={3} maxLength={40} pattern="[A-Za-z0-9][A-Za-z0-9._\-]{2,39}" autoCapitalize="none" autoComplete="off" spellCheck={false} value={username} onChange={e=>setUsername(e.target.value.toLowerCase())}/></label>}<label className="field"><span>{reset?'Nova senha':'Senha inicial'}</span><input required type="password" minLength={12} maxLength={72} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><p className="small muted">Senha de 12 a 72 caracteres. Não é necessário e-mail.</p><div className="button-row"><button className="btn primary" disabled={busy}>{busy?'Salvando…':reset?'Salvar nova senha':'Criar acesso'}</button>{reset&&<button type="button" className="btn secondary" disabled={busy} onClick={()=>{setReset(null);setPassword('');}}>Cancelar</button>}</div></form></div>;
}
