'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowDownToLine,ChevronLeft,ChevronRight,LockKeyhole,RefreshCw,Search,Store} from 'lucide-react';
import {Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle} from '@/components/ui/sheet';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {toast} from 'sonner';
import {api,dateTime,downloadCSV,money} from '@/lib/portal';
import {CustomerProfile} from '@/lib/customer';
type Directory={customers:CustomerProfile[];has_more:boolean;matched_count:number;total_count:number;price_summary:{name:string;grams:number;shops:number;average_price:number;minimum_price:number;maximum_price:number}[]};
export default function AdminCustomers(){
 const [data,setData]=useState<Directory|null>(null),[search,setSearch]=useState(''),[page,setPage]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<CustomerProfile|null>(null),[pin,setPin]=useState(''),[saving,setSaving]=useState(false),[exporting,setExporting]=useState(false);const sequence=useRef(0);
 async function load(){const id=++sequence.current;setBusy(true);setError('');try{const result=await api('admin_customers',{search,page},true);if(id===sequence.current)setData(result);}catch(e){if(id===sequence.current)setError(e instanceof Error?e.message:'Não foi possível carregar os clientes.');}finally{if(id===sequence.current)setBusy(false);}}
 useEffect(()=>{const t=setTimeout(()=>void load(),250);return()=>{clearTimeout(t);sequence.current++;};},[page,search]);
 async function exportData(){setExporting(true);try{const all:CustomerProfile[]=[];for(let p=0;p<10000;p++){const r:Directory=await api('admin_customers',{search,page:p},true);all.push(...r.customers);if(!r.has_more)break;}downloadCSV('clientes-precos-de-venda.csv',[['Loja','Telefone','Contato','Formato','Peso (g)','Preço de venda (R$)','Cadastro','Atualização'],...all.flatMap(c=>c.portions.map(p=>[c.store_name,c.phone,c.contact_name,p.name,p.grams,(p.price/100).toFixed(2),dateTime(c.created_at),dateTime(c.updated_at)]))]);}catch(e){toast.error(e instanceof Error?e.message:'Falha na exportação.');}finally{setExporting(false);}}
 return <><section className="admin-panel"><div className="panel-heading"><div><h2>Clientes e preços de venda</h2><p>{data?.total_count||0} lojas cadastradas · valores informados pelos clientes</p></div><div className="button-row"><button className="btn secondary" onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/>Atualizar</button><button className="btn secondary" onClick={exportData} disabled={exporting}><ArrowDownToLine size={16}/>{exporting?'Exportando…':'Exportar CSV'}</button></div></div><label className="search-box customer-search"><Search size={18}/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} placeholder="Buscar loja ou telefone" aria-label="Buscar clientes"/></label>{error?<p className="error-box">{error}</p>:busy?<div className="empty-state compact">Carregando clientes…</div>:data?.customers.length?<Table><TableHeader><TableRow><TableHead>Loja / contato</TableHead><TableHead>Telefone</TableHead><TableHead>Formatos de venda</TableHead><TableHead>Atualização</TableHead><TableHead/></TableRow></TableHeader><TableBody>{data.customers.map(c=><TableRow key={c.id}><TableCell><strong>{c.store_name}</strong><small className="table-sub">{c.contact_name||'—'}</small></TableCell><TableCell>{c.phone}</TableCell><TableCell>{c.portions.length}</TableCell><TableCell>{dateTime(c.updated_at)}</TableCell><TableCell><button className="btn secondary" onClick={()=>{setSelected(c);setPin('');}}>Ver cadastro<ChevronRight size={15}/></button></TableCell></TableRow>)}</TableBody></Table>:<div className="empty-state compact"><Store size={30}/><h3>{search?'Nenhuma loja encontrada':'Os cadastros aparecerão aqui'}</h3><p>Telefone, nome da loja e preços de cada formato ficam reunidos neste painel.</p></div>}<div className="pagination"><button className="btn secondary" disabled={!page||busy} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/>Anterior</button><span>Página {page+1} · {data?.matched_count||0} lojas</span><button className="btn secondary" disabled={!data?.has_more||busy} onClick={()=>setPage(p=>p+1)}>Próxima<ChevronRight size={16}/></button></div></section>
 <section className="admin-panel retail-insights"><div className="panel-heading"><div><h2>Por quanto as lojas vendem</h2><p>Toda a base de clientes · mesma descrição e mesmo peso · uma observação por loja</p></div></div>{data?.price_summary.length?<Table><TableHeader><TableRow><TableHead>Formato / peso</TableHead><TableHead className="numeric">Lojas</TableHead><TableHead className="numeric">Preço médio</TableHead><TableHead className="numeric">Menor</TableHead><TableHead className="numeric">Maior</TableHead></TableRow></TableHeader><TableBody>{data.price_summary.map((p,i)=><TableRow key={p.name+p.grams+i}><TableCell><strong>{p.name}</strong><small className="table-sub">{p.grams} g de sorvete</small></TableCell><TableCell className="numeric">{p.shops}</TableCell><TableCell className="numeric"><b>{money(p.average_price)}</b></TableCell><TableCell className="numeric">{money(p.minimum_price)}</TableCell><TableCell className="numeric">{money(p.maximum_price)}</TableCell></TableRow>)}</TableBody></Table>:<p className="table-note">As médias aparecerão quando os clientes informarem seus preços.</p>}<p className="table-note">Preços declarados, sem ponderação por vendas. As lojas podem atualizar os valores em “Minha loja”.</p></section>
 <Sheet open={!!selected} onOpenChange={v=>{if(!v){setSelected(null);setPin('');}}}><SheetContent className="overflow-y-auto w-full sm:max-w-xl"><SheetHeader><SheetTitle>{selected?.store_name}</SheetTitle><SheetDescription>Cadastro e preços informados pela loja.</SheetDescription></SheetHeader>{selected&&<div className="detail-body"><div className="customer-card"><p>{selected.phone}<br/>{selected.contact_name||'Contato não informado'}</p><small>Cadastro: {dateTime(selected.created_at)}<br/>Atualização: {dateTime(selected.updated_at)}</small></div><div className="order-lines">{selected.portions.map(p=><div key={p.id}><div><strong>{p.name}</strong><small>{p.grams} g de sorvete{p.id===selected.preferred_portion_id?' · cenário preferido':''}</small></div><b>{money(p.price)}</b></div>)}</div><form className="customer-pin-reset" onSubmit={async e=>{e.preventDefault();setSaving(true);try{await api('reset_customer_pin',{customer_id:selected.id,pin},true);setPin('');toast.success('PIN redefinido. Os aparelhos anteriores foram desconectados.');}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível redefinir o PIN.');}finally{setSaving(false);}}}><h3><LockKeyhole size={18}/>Recuperação de acesso</h3><p className="small muted">Confirme com o responsável pela loja antes de redefinir. O novo PIN encerra os acessos salvos nos aparelhos anteriores. Compartilhe-o diretamente com o cliente.</p><label className="field"><span>Novo PIN de 6 números</span><input type="password" autoComplete="new-password" inputMode="numeric" pattern="[0-9]{6}" minLength={6} maxLength={6} required value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))}/></label><button className="btn secondary" disabled={saving}>{saving?'Salvando…':'Redefinir PIN e encerrar acessos'}</button></form></div>}</SheetContent></Sheet></>;
}
