'use client';
import {useState} from 'react';
import {PenLine,Plus} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {toast} from 'sonner';
import {api,Catalog,money,moneyInput,cents} from '@/lib/portal';
import {UpsellRule} from '@/lib/retention';
import {Choice} from './controls';
export default function AdminUpsellRules({catalog,onSaved}:{catalog:Catalog;onSaved:()=>Promise<unknown>}){
 const [editing,setEditing]=useState<Partial<UpsellRule>|null>(null),[price,setPrice]=useState(''),[busy,setBusy]=useState(false);
 const products=catalog.products.filter(p=>p.active),selected=products.find(p=>p.id===editing?.product_id);
 function edit(rule:Partial<UpsellRule>){setEditing(rule);setPrice(moneyInput(rule.price??null));}
 async function save(e:React.FormEvent){e.preventDefault();if(!editing)return;setBusy(true);try{await api('save_upsell_rule',{rule:{...editing,price:cents(price)}},true);await onSaved();setEditing(null);toast.success('Regra salva.');}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}
 return <><section className="admin-panel contextual-rules"><div className="panel-heading"><div><h2>Sugestões conforme o carrinho</h2><p>Mostre um complemento compatível. O cliente sempre escolhe se deseja adicionar.</p></div><button className="btn secondary" onClick={()=>edit({trigger_product_id:'',product_id:'',flavor_id:null,title:'Complete seu pedido',description:'',price:null,priority:10,active:true})}><Plus size={16}/>Nova regra</button></div><label className="toggle-row"><div><strong>Ativar sugestões por produto</strong><p>Uma sugestão por vez, pela menor prioridade. A sugestão geral fica como alternativa.</p></div><Switch aria-label="Ativar sugestões conforme o carrinho" checked={!!catalog.settings.contextual_upsell_enabled} disabled={busy} onCheckedChange={async enabled=>{setBusy(true);try{await api('toggle_contextual_upsell',{enabled},true);await onSaved();toast.success(enabled?'Sugestões ativadas.':'Sugestões desativadas.');}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setBusy(false);}}}/></label>
 {(catalog.upsell_rules||[]).map(r=><div className="rule-row" key={r.id}><div><strong>{catalog.products.find(p=>p.id===r.trigger_product_id)?.name||'Produto indisponível'}</strong><p>Sugerir {catalog.products.find(p=>p.id===r.product_id)?.name||'Produto indisponível'}{r.flavor_id?' · '+(catalog.flavors.find(f=>f.id===r.flavor_id)?.name||'Sabor indisponível'):''}</p><small>{r.active?'Ativa':'Pausada'} · prioridade {r.priority} · {r.price?money(r.price):'preço atual do catálogo'}</small></div><button className="btn secondary" onClick={()=>edit(r)}><PenLine size={15}/>Editar</button></div>)}
 {!catalog.upsell_rules?.length&&<p className="table-note">Cadastre qual produto deve sugerir cada complemento.</p>}</section>
 <Dialog open={!!editing} onOpenChange={v=>{if(!v&&!busy)setEditing(null);}}><DialogContent className="admin-dialog max-h-[92dvh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{editing?.id?'Editar regra':'Nova regra'}</DialogTitle><DialogDescription>O complemento aparece somente quando o produto escolhido está no carrinho.</DialogDescription></DialogHeader>{editing&&<form className="settings-form" onSubmit={save}><label className="field"><span>Quando o carrinho tiver</span><Choice label="Produto que ativa a sugestão" value={editing.trigger_product_id||'none'} onChange={v=>setEditing({...editing,trigger_product_id:v==='none'?'':v})} options={[{value:'none',label:'Selecione o produto'},...products.map(p=>({value:p.id,label:p.name}))]}/></label><label className="field"><span>Sugerir este complemento</span><Choice label="Complemento sugerido" value={editing.product_id||'none'} onChange={v=>setEditing({...editing,product_id:v==='none'?'':v,flavor_id:null})} options={[{value:'none',label:'Selecione o complemento'},...products.filter(p=>p.id!==editing.trigger_product_id).map(p=>({value:p.id,label:p.name}))]}/></label>{selected?.has_flavors&&<label className="field"><span>Sabor do complemento</span><Choice label="Sabor sugerido" value={editing.flavor_id||'none'} onChange={v=>setEditing({...editing,flavor_id:v==='none'?null:v})} options={[{value:'none',label:'Selecione o sabor'},...catalog.flavors.filter(f=>f.product_id===selected.id&&f.active).map(f=>({value:f.id,label:f.name}))]}/></label>}
 <label className="field"><span>Título para o cliente</span><input required maxLength={100} value={editing.title||''} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label className="field"><span>Texto de apoio (opcional)</span><textarea rows={2} maxLength={300} value={editing.description||''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><div className="form-grid"><label className="field"><span>Preço especial (R$, opcional)</span><input inputMode="decimal" pattern="[0-9]+([.,][0-9]{1,2})?" value={price} onChange={e=>setPrice(e.target.value)} placeholder="Preço do catálogo"/></label><label className="field"><span>Prioridade (menor primeiro)</span><input type="number" min={0} max={999} step={1} required value={editing.priority??0} onChange={e=>setEditing({...editing,priority:Number(e.target.value)})}/></label></div><label className="toggle-row"><strong>Regra ativa</strong><Switch checked={!!editing.active} onCheckedChange={active=>setEditing({...editing,active})} aria-label="Regra ativa"/></label><button className="btn primary wide" disabled={busy}>{busy?'Salvando…':'Salvar regra'}</button></form>}</DialogContent></Dialog></>;
}
