'use client';
import {useEffect,useRef,useState} from 'react';
import {Bell,ChevronLeft,ChevronRight,ExternalLink,RefreshCw,Search} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle} from '@/components/ui/sheet';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {toast} from 'sonner';
import {api,dateTime,money} from '@/lib/portal';
import {Choice} from './controls';
type Opportunity={customer_id:string;store_name:string;phone:string;contact_name:string;cycle_days:number|null;manual_days:number|null;cycle_source:string;last_purchase:string|null;due_at:string|null;days_overdue?:number;revision?:number;updated_at?:string;total?:number;items?:{name:string;quantity:number;mode:string;bundle_units:number;unit_price:number}[]};
type Queue={rows:Opportunity[];total:number;has_more:boolean};
export default function AdminRetention(){
 const [kind,setKind]=useState('reorder'),[search,setSearch]=useState(''),[page,setPage]=useState(0),[data,setData]=useState<Queue|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<Opportunity|null>(null),[days,setDays]=useState(''),[saving,setSaving]=useState(false);const seq=useRef(0);
 async function load(){const n=++seq.current;setBusy(true);setError('');try{const result=await api('retention_queue',{kind,search,page},true);if(n===seq.current)setData(result);}catch(e){if(n===seq.current)setError(e instanceof Error?e.message:'Não foi possível carregar.');}finally{if(n===seq.current)setBusy(false);}}
 useEffect(()=>{const t=setTimeout(()=>void load(),250);return()=>{clearTimeout(t);seq.current++;};},[kind,search,page]);
 function select(row:Opportunity){setSelected(row);setDays(row.manual_days?.toString()||'');}
 async function action(name:string,values:Record<string,unknown>){setSaving(true);try{await api(name,values,true);setSelected(null);await load();toast.success(name==='dismiss_cart'?'Carrinho arquivado. Uma nova alteração do cliente fará ele reaparecer.':name==='snooze_reorder'?'Lembrete adiado por 7 dias.':'Frequência salva.');}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setSaving(false);}}
 const message=selected?(kind==='carts'?`Olá! Tudo bem? Aqui é da Yogomarcas. Precisa de ajuda para concluir o pedido da ${selected.store_name}?`:`Olá! Tudo bem? Aqui é da Yogomarcas. Como está o estoque da ${selected.store_name}? Podemos ajudar a montar seu próximo pedido?`):'';
 return <><section className="admin-panel"><div className="panel-heading"><div><h2>Oportunidades de atendimento</h2><p>{kind==='reorder'?'Compras confirmadas com reposição prevista para agora.':kind==='carts'?'Carrinhos identificados sem alteração há pelo menos 2 horas.':'Defina a frequência por cliente ou use o histórico de compras.'}</p></div><button className="btn secondary" disabled={busy} onClick={()=>void load()}><RefreshCw size={16}/>Atualizar</button></div>
 <Tabs value={kind} onValueChange={v=>{setKind(v);setPage(0);setSelected(null);}}><TabsList className="retention-tabs"><TabsTrigger value="reorder">Recompra</TabsTrigger><TabsTrigger value="carts">Carrinhos pendentes</TabsTrigger><TabsTrigger value="frequency">Frequência dos clientes</TabsTrigger></TabsList></Tabs>
 <label className="search-box customer-search"><Search size={18}/><input aria-label="Buscar oportunidades por loja ou telefone" placeholder="Buscar loja ou telefone" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label>
 {error?<div className="error-box" role="alert">{error}</div>:busy?<p role="status">Carregando…</p>:data?.rows.length?<Table><TableHeader><TableRow><TableHead>Loja</TableHead><TableHead>{kind==='carts'?'Carrinho':'Última compra'}</TableHead><TableHead>{kind==='carts'?'Última alteração':'Frequência'}</TableHead><TableHead/></TableRow></TableHeader><TableBody>{data.rows.map(r=><TableRow key={r.customer_id}><TableCell><strong>{r.store_name}</strong><small className="table-sub">{r.phone}</small></TableCell><TableCell>{kind==='carts'?<><b>{money(r.total||0)}</b><small className="table-sub">{r.items?.length||0} itens</small></>:r.last_purchase?dateTime(r.last_purchase):'Sem compra confirmada'}</TableCell><TableCell>{kind==='carts'?dateTime(r.updated_at!):<>{r.cycle_days?`A cada ${r.cycle_days} dias`:'Ainda não definida'}<small className="table-sub">{kind==='reorder'?`${r.days_overdue||0} dias de atraso`:r.cycle_source==='history'?'Calculada pelo histórico':r.cycle_source==='manual'?'Definida pela equipe':'Aguardando histórico'}</small></>}</TableCell><TableCell><button className="btn secondary" onClick={()=>select(r)}>{kind==='frequency'?'Ajustar':'Ver detalhes'}<ChevronRight size={15}/></button></TableCell></TableRow>)}</TableBody></Table>:<div className="empty-state compact"><Bell size={28}/><h3>{kind==='reorder'?'Nenhuma recompra atrasada':kind==='carts'?'Nenhum carrinho pendente':'Nenhuma loja encontrada'}</h3><p>{kind==='reorder'?'Os alertas aparecerão conforme as compras forem confirmadas. Você também pode definir frequências na aba ao lado.':kind==='carts'?'Pedidos já preparados para o WhatsApp ficam na aba Pedidos.':'Os novos cadastros aparecerão aqui.'}</p></div>}
 <div className="pagination"><button className="btn secondary" disabled={!page||busy} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/>Anterior</button><span>Página {page+1} · {data?.total||0} registros</span><button className="btn secondary" disabled={!data?.has_more||busy} onClick={()=>setPage(p=>p+1)}>Próxima<ChevronRight size={16}/></button></div></section>
 <Sheet open={!!selected} onOpenChange={v=>{if(!v&&!saving)setSelected(null);}}><SheetContent className="order-detail overflow-y-auto w-full sm:max-w-xl"><SheetHeader><SheetTitle>{selected?.store_name}</SheetTitle><SheetDescription>{kind==='carts'?'Itens salvos pelo cliente.':'Acompanhamento da próxima compra.'}</SheetDescription></SheetHeader>{selected&&<div className="detail-body"><p>{selected.contact_name}<br/>{selected.phone}</p>
 {kind==='carts'?<><div className="order-lines">{selected.items?.map((i,n)=><div key={n}><div><strong>{i.name}</strong><small>{i.quantity} × {i.mode==='bundle'?`fardo de ${i.bundle_units} pacotes`:'pacote'}</small></div><b>{money(i.quantity*i.unit_price)}</b></div>)}</div><div className="checkout-total"><span>Valor na última alteração</span><strong>{money(selected.total||0)}</strong></div><p className="small muted">Atualizado em {dateTime(selected.updated_at!)}. Preços e disponibilidade podem mudar.</p></>:<form className="settings-form" onSubmit={e=>{e.preventDefault();void action('save_customer_cycle',{customer_id:selected.customer_id,cycle_days:days?Number(days):null});}}><p>{selected.last_purchase?`Última compra: ${dateTime(selected.last_purchase)}`:'Nenhuma compra confirmada.'}</p><label className="field"><span>Frequência de compra</span><Choice label="Frequência de recompra" value={['','7','14','30','60','90'].includes(days)?days||'auto':'custom'} onChange={v=>setDays(v==='auto'?'':v==='custom'?'21':v)} options={[{value:'auto',label:'Calcular pelo histórico'},{value:'7',label:'1 semana'},{value:'14',label:'2 semanas'},{value:'30',label:'30 dias'},{value:'60',label:'60 dias'},{value:'90',label:'90 dias'},{value:'custom',label:'Personalizar'}]}/></label>{days&&<label className="field"><span>Intervalo em dias</span><input type="number" min={1} max={365} step={1} required value={days} onChange={e=>setDays(e.target.value)}/></label>}<p className="small muted">O cálculo automático usa a mediana dos intervalos das últimas 6 datas de compra. São necessárias pelo menos 3 datas com pedidos confirmados ou concluídos.</p><button className="btn primary" disabled={saving}>Salvar frequência</button></form>}
 <a className="btn secondary wide" href={`https://wa.me/${selected.phone}?text=${encodeURIComponent(message)}`} target="_blank" rel="noreferrer">Abrir WhatsApp<ExternalLink size={16}/></a>
 {kind==='carts'?<button className="btn text-button" disabled={saving} onClick={()=>void action('dismiss_cart',{customer_id:selected.customer_id,revision:selected.revision})}>Arquivar este carrinho</button>:kind==='reorder'?<button className="btn text-button" disabled={saving} onClick={()=>void action('snooze_reorder',{customer_id:selected.customer_id})}>Lembrar novamente em 7 dias</button>:null}
 </div>}</SheetContent></Sheet></>;
}
