'use client';
import {useEffect,useRef,useState} from 'react';
import {Check,ImagePlus,LoaderCircle,Package,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Switch} from '@/components/ui/switch';
import {Line,Product,cents,money,moneyInput} from '@/lib/portal';
import {Choice} from './controls';
function Field({title,children}:{title:string;children:React.ReactNode}){return <label className="field"><span>{title}</span>{children}</label>;}
function Flag({title,description,checked,onChange}:{title:string;description?:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="toggle-row"><div><strong>{title}</strong>{description&&<p>{description}</p>}</div><Switch checked={checked} onCheckedChange={onChange} aria-label={title}/></label>;}
function Price({value,onChange}:{value:number|null;onChange:(v:number|null)=>void}){const [draft,setDraft]=useState(()=>moneyInput(value)),last=useRef(value);useEffect(()=>{if(value!==last.current){setDraft(moneyInput(value));last.current=value;}},[value]);return <input inputMode="decimal" pattern="[0-9]+([.,][0-9]{1,2})?" value={draft} placeholder="0,00" onChange={e=>{const v=e.target.value;setDraft(v);if(v===''||/^[0-9]+([.,][0-9]{0,2})?$/.test(v)){last.current=cents(v);onChange(last.current);}}}/>;}
export default function AdminProductEditor({product:p,lines,busy,uploadBusy,onChange,onClose,onSave,onUpload,onDelete}:{product:Product|null;lines:Line[];busy:boolean;uploadBusy:boolean;onChange:(p:Product)=>void;onClose:()=>void;onSave:(e:React.FormEvent)=>void;onUpload:(file:File)=>void;onDelete:(p:Product)=>void}){
 const locked=busy||uploadBusy;
 return <Dialog open={!!p} onOpenChange={open=>{if(!open&&!locked)onClose();}}><DialogContent className="admin-dialog catalog-editor sm:max-w-3xl" onEscapeKeyDown={e=>{if(locked)e.preventDefault();}} onPointerDownOutside={e=>{if(locked)e.preventDefault();}}><DialogHeader><div className="editor-kicker"><Package size={17}/>CATÁLOGO</div><DialogTitle>{p?.id?'Editar produto':'Novo produto'}</DialogTitle><DialogDescription>Organize as informações, a foto e as condições de venda.</DialogDescription></DialogHeader>{p&&<form onSubmit={onSave} className="catalog-editor-form"><div className="catalog-editor-scroll"><fieldset disabled={locked} className="editor-fields"><section className="editor-section"><div className="editor-section-heading"><h3>Dados do produto</h3><span>* Obrigatório</span></div><div className="image-editor">{p.image_url?<img src={p.image_url} alt={p.name||'Foto do produto'}/>:<ImagePlus size={40}/>}<div><strong>Foto no catálogo</strong><label className="btn secondary upload-button">{uploadBusy?<LoaderCircle className="spin" size={17}/>:<ImagePlus size={17}/>}Enviar foto<input type="file" accept="image/jpeg,image/png,image/webp" disabled={locked} onChange={e=>{if(e.target.files?.[0])onUpload(e.target.files[0]);}}/></label><p className="small muted">JPG, PNG ou WebP · até 5 MB</p>{p.image_url&&<button type="button" className="text-button" onClick={()=>onChange({...p,image_url:''})}>Remover foto</button>}</div></div><div className="form-grid"><Field title="Nome do produto *"><input required maxLength={200} value={p.name} onChange={e=>onChange({...p,name:e.target.value})} placeholder="Ex.: Expresso Italiano"/></Field><Field title="Código interno *"><input required maxLength={60} value={p.sku} onChange={e=>onChange({...p,sku:e.target.value.toUpperCase()})} placeholder="Ex.: YOGO-EI"/></Field><Field title="Categoria *"><Choice label="Categoria do produto" value={p.line_id} onChange={line_id=>onChange({...p,line_id})} options={lines.map(l=>({value:l.id,label:l.name+(!l.active?' (oculta)':'')}))}/></Field><Field title="Nome da unidade"><input required maxLength={40} value={p.package_label} onChange={e=>onChange({...p,package_label:e.target.value})} placeholder="Pacote, bisnaga, unidade…"/></Field></div><Field title="Descrição"><textarea rows={3} maxLength={2000} value={p.description} onChange={e=>onChange({...p,description:e.target.value})} placeholder="Conte o que o cliente precisa saber sobre esta linha."/></Field><Flag title="Esta linha tem vários sabores" description="Os sabores e seus preços são cadastrados em Gerenciar sabores." checked={!!p.has_flavors} onChange={has_flavors=>onChange({...p,has_flavors,package_price:has_flavors?null:p.package_price,bundle_price:has_flavors?null:p.bundle_price})}/></section>
 <section className="editor-section"><div className="editor-section-heading"><h3>Preço e rendimento</h3></div>{p.has_flavors?<p className="editor-hint">Defina o preço de cada sabor em <strong>Gerenciar sabores</strong>.</p>:<div className="form-grid"><Field title={`Preço por ${p.package_label.toLowerCase()} (R$)`}><Price value={p.package_price} onChange={package_price=>onChange({...p,package_price})}/></Field><Field title="Peso por pacote (g)"><input type="number" min={1} max={100000} step={1} value={p.package_weight_grams??''} onChange={e=>onChange({...p,package_weight_grams:e.target.value?Number(e.target.value):null})} placeholder="Ex.: 1850"/></Field></div>}<div className="computed-value"><div><span>Fardo de 5 pacotes</span><small>Valor calculado automaticamente</small></div><strong>{!p.has_flavors&&p.package_price?money(p.package_price*5):'5 × preço do pacote'}</strong></div><Flag title="Incluir na estimativa de lucro" description="Use apenas nas bases e informe o rendimento de um pacote após o preparo." checked={p.yield_grams!==null} onChange={enabled=>onChange({...p,yield_grams:enabled?6000:null,yield_min_grams:enabled?5500:null})}/>{p.yield_grams!==null&&<div className="form-grid"><Field title="Rendimento mínimo (g por pacote)"><input required type="number" min={1} max={p.yield_grams||100000} step={1} value={p.yield_min_grams??''} onChange={e=>onChange({...p,yield_min_grams:e.target.value?Number(e.target.value):null})}/></Field><Field title="Rendimento máximo (g por pacote)"><input required type="number" min={p.yield_min_grams||1} max={100000} step={1} value={p.yield_grams??''} onChange={e=>onChange({...p,yield_grams:e.target.value?Number(e.target.value):0})}/></Field></div>}</section>
 <section className="editor-section"><div className="editor-section-heading"><h3>Disponibilidade</h3></div><Flag title="Visível no catálogo" checked={p.active} onChange={active=>onChange({...p,active})}/><Flag title="Disponível para pedido" checked={p.available} onChange={available=>onChange({...p,available})}/><Field title="Ordem de exibição"><input type="number" min={0} max={999} step={1} value={p.position} onChange={e=>onChange({...p,position:Number(e.target.value)})}/></Field></section></fieldset></div><footer className="editor-footer">{p.id&&<button type="button" className="btn danger-outline" disabled={locked} onClick={()=>onDelete(p)}><Trash2 size={16}/>Excluir produto</button>}<div className="editor-primary-actions"><button type="button" className="btn secondary" disabled={locked} onClick={onClose}>Cancelar</button><button type="submit" className="btn primary" disabled={locked}>{busy?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>}Salvar produto</button></div></footer></form>}</DialogContent></Dialog>;
}
