'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,LoaderCircle,Plus,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {toast} from 'sonner';
import {api,moneyInput,PortalError} from '@/lib/portal';
import {CustomerProfile,customerApi,newDeviceToken,normalizePhone,PORTION_OPTIONS,readIdentity,saveIdentity} from '@/lib/customer';
import Disclosure from './disclosure';
import {SalePortion} from '@/lib/projection';
type DraftPortion={id:string;name:string;grams:string;price:string;enabled:boolean};
const drafts=(p:CustomerProfile|null):DraftPortion[]=>{
 const saved=p?.portions||[];return [...PORTION_OPTIONS.map(o=>{const v=saved.find(v=>v.id===o.id);return {id:o.id,name:v?.name||o.name,grams:v?String(v.grams):o.grams?String(o.grams):'',price:v?moneyInput(v.price):'',enabled:!!v||!p&&o.id==='small_cone'};}),...saved.filter(v=>!PORTION_OPTIONS.some(o=>o.id===v.id)).map(v=>({...v,grams:String(v.grams),price:moneyInput(v.price),enabled:true}))];
};
export default function CustomerOnboarding({open,profile,onOpenChange,onSaved,restoreError,onRetry,allowClose=false}:{open:boolean;profile:CustomerProfile|null;onOpenChange:(v:boolean)=>void;onSaved:(p:CustomerProfile)=>void;restoreError:string;onRetry:()=>void;allowClose?:boolean}){
 const [step,setStep]=useState(0),[phone,setPhone]=useState(''),[store,setStore]=useState(''),[name,setName]=useState(''),[pin,setPin]=useState(''),[existing,setExisting]=useState(false),[rows,setRows]=useState<DraftPortion[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const token=useRef('');
 useEffect(()=>{if(open){setStep(profile?1:0);setPhone(profile?.phone||readIdentity()?.phone||'');setStore(profile?.store_name||'');setName(profile?.contact_name||'');setPin('');setExisting(false);setRows(drafts(profile));setError('');token.current=newDeviceToken();}},[open,profile?.id]);
 const closeAllowed=!!profile||allowClose;
 async function submit(e:React.FormEvent){e.preventDefault();setError('');
 if(step===0){const normalized=normalizePhone(phone);if(!normalized){setError('Informe o telefone com DDD.');return;}setBusy(true);try{const r=await api('customer_start',{phone:normalized});setPhone(normalized);setExisting(r.exists);setStep(1);}catch(e){setError(e instanceof Error?e.message:'Não foi possível continuar.');}finally{setBusy(false);}return;}
 if(existing&&!profile){setBusy(true);try{const r=await api('customer_login',{phone,pin,device_token:token.current});const remembered=saveIdentity(phone,token.current);onSaved(r.profile);onOpenChange(false);if(!remembered)toast.info('Seu navegador não permitiu lembrar este acesso. O cadastro continua salvo.');}catch(e){setError(e instanceof Error?e.message:'Não foi possível entrar.');}finally{setBusy(false);}return;}
 if(step===1){if(store.trim().length<2){setError('Informe o nome da loja.');return;}if(!profile&&!/^\d{6}$/.test(pin)){setError('Crie um PIN de 6 números.');return;}setStep(2);return;}
 const enabled=rows.filter(r=>r.enabled);if(!enabled.length){setError('Selecione pelo menos um formato que sua loja vende.');return;}
 const portions:SalePortion[]=[];
 for(const r of enabled){const grams=Number(r.grams),price=Math.round(Number(r.price.replace(',','.'))*100);if(r.name.trim().length<2||!r.grams||!Number.isInteger(grams)||grams<10||grams>10000||!r.price||!/^[0-9]+([.,][0-9]{1,2})?$/.test(r.price)||!Number.isSafeInteger(price)||price<1||price>1000000){setError(`Confira nome, peso e preço de ${r.name||'cada formato'}.`);return;}portions.push({id:r.id,name:r.name.trim(),grams,price});}
 setBusy(true);try{const payload={store_name:store.trim(),contact_name:name.trim(),portions,preferred_portion_id:profile?.preferred_portion_id||portions[0].id};let result;
 if(profile)result=await customerApi('customer_update',payload);else{saveIdentity(phone,token.current);result=await api('customer_register',{...payload,phone,pin,device_token:token.current});}
 const remembered=profile?true:saveIdentity(phone,token.current);onSaved(result.profile);onOpenChange(false);toast.success(profile?'Dados da loja atualizados.':'Sua loja está cadastrada.');if(!remembered)toast.info('O cadastro foi salvo, mas este navegador não permitiu lembrar o acesso.');
 }catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar seu cadastro.');if(e instanceof PortalError&&e.status===401&&profile)onRetry();}finally{setBusy(false);}}
 const patch=(index:number,values:Partial<DraftPortion>)=>setRows(items=>items.map((r,i)=>i===index?{...r,...values}:r));
 return <Dialog open={open} onOpenChange={v=>{if(closeAllowed&&!busy)onOpenChange(v);}}><DialogContent showCloseButton={closeAllowed} className="customer-dialog max-h-[94dvh] overflow-y-auto sm:max-w-2xl" onEscapeKeyDown={e=>{if(!closeAllowed)e.preventDefault();}} onInteractOutside={e=>{if(!closeAllowed)e.preventDefault();}}><DialogHeader><DialogTitle>{restoreError?'Vamos recuperar seu cadastro':step===0?'Qual é o telefone da sua loja?':existing&&!profile?'Bem-vindo de volta':step===1?'Como sua loja se chama?':'Por quanto você vende seu sorvete?'}</DialogTitle><DialogDescription>{restoreError?'Seu acesso continua salvo neste aparelho. Tente carregar novamente.':step===0?'Vamos lembrar sua loja neste aparelho.':existing&&!profile?'Digite o PIN da sua loja.':step===1?'Vamos usar esses dados nos seus pedidos.':'Selecione o que vende e informe seus preços.'}</DialogDescription></DialogHeader>
 {restoreError?<div className="settings-form"><p className="error-box">{restoreError}</p><button className="btn primary" onClick={onRetry}>Tentar novamente</button><p className="small muted">Se precisar de ajuda, <a href="https://wa.me/554532541200" target="_blank" rel="noreferrer">fale com nossa equipe</a>.</p></div>:<><div className="onboarding-progress" aria-label={`Etapa ${step+1} de ${existing?2:3}`}>{[0,1,...(existing?[]:[2])].map(n=><span key={n} className={step>=n?'done':''}/>)}</div><form onSubmit={submit} className="onboarding-form">
 {step===0&&<label className="field"><span>WhatsApp com DDD</span><input type="tel" inputMode="tel" autoComplete="tel" required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(45) 99999-9999" maxLength={25} autoFocus/></label>}
 {step===1&&<>{!existing&&<><label className="field"><span>Nome da loja *</span><input required autoComplete="organization" value={store} onChange={e=>setStore(e.target.value)} maxLength={160} autoFocus/></label><label className="field"><span>Seu nome (opcional)</span><input autoComplete="name" value={name} onChange={e=>setName(e.target.value)} maxLength={120}/></label><div className="identified-phone"><Check size={16}/>{phone}</div></>}{!profile&&<label className="field"><span>{existing?'PIN de acesso':'Crie seu PIN de acesso'} *</span><input type="password" inputMode="numeric" pattern="[0-9]{6}" minLength={6} maxLength={6} required autoComplete={existing?'current-password':'new-password'} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} placeholder="6 números" autoFocus={existing}/><small>{existing?'Esqueceu o PIN? Peça ajuda à equipe pelo WhatsApp.':'Use este PIN para entrar em outro aparelho.'}</small></label>}</>}
 {step===2&&<><p className="small muted">Os pesos já vêm preenchidos. Ajuste se precisar.</p><div className="portion-editor">{rows.map((r,i)=><div className={`portion-row ${r.enabled?'enabled':''}`} key={r.id}><div className="portion-row-title"><label><Checkbox checked={r.enabled} onCheckedChange={v=>patch(i,{enabled:v===true})} aria-label={`Vendo ${r.name}`}/>{r.id.startsWith('custom_')?<input aria-label="Nome do formato" value={r.name} onChange={e=>patch(i,{name:e.target.value})} placeholder="Ex.: pote de 500 g" maxLength={80}/>:<strong>{r.name}</strong>}</label>{r.id.startsWith('custom_')&&<button className="icon-button" type="button" aria-label="Remover formato" onClick={()=>setRows(items=>items.filter((_,n)=>n!==i))}><Trash2 size={15}/></button>}</div>{r.enabled&&<div className="form-grid"><label className="field"><span>Peso do sorvete (g)</span><input type="number" min="10" max="10000" step="1" required value={r.grams} onChange={e=>patch(i,{grams:e.target.value})} placeholder={r.id==='small_cone'?'100':'Informe o peso'}/></label><label className="field"><span>Preço de venda (R$)</span><input type="text" inputMode="decimal" pattern="[0-9]+([.,][0-9]{1,2})?" required value={r.price} onChange={e=>patch(i,{price:e.target.value})} placeholder="0,00"/></label></div>}</div>)}</div><button type="button" className="btn secondary" disabled={rows.length>=12} onClick={()=>setRows([...rows,{id:'custom_'+crypto.randomUUID().slice(0,8),name:'',grams:'',price:'',enabled:true}])}><Plus size={16}/>Outro formato</button><Disclosure title="Como informar o peso"><p className="small muted">Use o peso do sorvete em gramas, sem embalagem ou cobertura. O volume do pote em ml não equivale ao peso em gramas.</p></Disclosure></>}
 {error&&<p className="error-box" role="alert">{error}</p>}<div className="onboarding-actions">{step>(profile?1:0)&&<button type="button" className="btn secondary" disabled={busy} onClick={()=>{setStep(step-1);setError('');}}> <ArrowLeft size={16}/>Voltar</button>}<button className="btn primary" disabled={busy}>{busy?<LoaderCircle size={17} className="spin"/>:null}{existing&&!profile?'Entrar':step===2?(profile?'Salvar alterações':'Concluir cadastro'):'Continuar'}<ArrowRight size={17}/></button></div><p className="onboarding-privacy">Seus dados e preços serão usados no atendimento à sua loja. <a href="/privacidade" target="_blank">Privacidade</a></p></form></>}
 </DialogContent></Dialog>;
}
