'use client';
import {sessionStore} from '@/lib/browser-storage';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRight,ArrowRightLeft,Check,ChevronDown,ChevronRight,Clock3,Headphones,LoaderCircle,Package,Search,Settings2,ShoppingBag,Store,Trash2,X} from 'lucide-react';
import {Sheet,SheetContent,SheetDescription,SheetHeader,SheetTitle} from '@/components/ui/sheet';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster,toast} from 'sonner';
import {Brand,Choice,Quantity,DualQuantity} from './controls';
import {api,cartKey,groupCart,CartGroup,convertBundleToPackages,variantKey,setVariantQuantity,itemName,normalizeSearch,startingPrice,variantProduct,Flavor,CartItem,Catalog,getCatalog,money,PortalError,Product,ResolvedItem,resolveCart,sessionId,STATES,track} from '@/lib/portal';
import {DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuLabel,DropdownMenuSeparator,DropdownMenuTrigger} from '@/components/ui/dropdown-menu';
import Disclosure from './disclosure';
import FlavorPicker from './flavor-picker';
import CustomerHistory from './customer-history';
import CartSuggestion from './cart-suggestion';
import {useCartSync,useFavorites} from '@/hooks/use-shopping';
import {cartOffer,mergeRepeat} from '@/lib/retention';
import CustomerOnboarding from './customer-onboarding';
import ProjectionCard from './projection-card';
import {CustomerProfile,customerApi,forgetIdentity,readIdentity,restoreCustomer} from '@/lib/customer';
const CART_KEY='yogomarcas-cart-v1';
const EMPTY_CUSTOMER={name:'',company:'',phone:'',city:'',state:'PR',code:'',notes:''};
function Photo({product,large=false}:{product:Product;large?:boolean}){const [failed,setFailed]=useState(false);return <div className={`product-photo ${large?'large':''} ${product.sku==='LUB'?'support':''} ${product.image_url.startsWith('/assets/catalog-')?'catalog-photo':''}`}>{product.image_url&&!failed?<img src={product.image_url} alt={product.name} loading="lazy" onError={()=>setFailed(true)}/>:<div className="no-photo"><Package size={large?60:40} strokeWidth={1}/><span>{product.package_label}</span></div>}</div>;}
function PackPicker({p,mode,setMode}:{p:Product;mode:'package'|'bundle';setMode:(m:'package'|'bundle')=>void}){if(p.bundle_enabled===false||!p.bundle_price||!p.bundle_units)return null;return <RadioGroup value={mode} onValueChange={v=>setMode(v as 'package'|'bundle')} className="pack-picker" aria-label={`Apresentação de ${p.name}`}>{(['package','bundle'] as const).map(m=><label key={m} className={`pack-option ${mode===m?'selected':''} ${m==='bundle'&&(!p.bundle_price||!p.bundle_units)?'unavailable':''}`}><RadioGroupItem value={m} disabled={m==='bundle'&&(!p.bundle_price||!p.bundle_units)}/><span>{m==='package'?p.package_label:'Fardo'}{m==='bundle'&&p.bundle_units?<small>{p.bundle_units} pacotes</small>:null}</span></label>)}</RadioGroup>;}
function ProductCard({p,flavors,onAdd,onDetails,enabled}:{p:Product;flavors:Flavor[];onAdd:(p:Product,m:'package'|'bundle',q:number)=>void;onDetails:(p:Product)=>void;enabled:boolean}){
 const [selectedMode,setMode]=useState<'package'|'bundle'>('package'),[qty,setQty]=useState(1);const ref=useRef<HTMLElement>(null);
 const mode=p.bundle_enabled===false?'package':selectedMode;
 useEffect(()=>{const el=ref.current;if(!el)return;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){track('product_view',p.id,true);observer.disconnect();}},{threshold:.4});observer.observe(el);return()=>observer.disconnect();},[p.id]);
 const price=p.has_flavors?startingPrice(p,flavors):mode==='package'?p.package_price:p.bundle_price;const available=enabled&&p.available&&!!price;
 return <article className="product-card" ref={ref}>
  <button className="photo-button" onClick={()=>onDetails(p)} aria-label={`Ver ${p.name}`}><Photo product={p}/></button>
  <div className="product-body"><button onClick={()=>onDetails(p)} className="product-name">{p.name}</button>
   <p className="product-meta">{p.has_flavors?`${flavors.filter(f=>f.product_id===p.id&&f.active).length} sabores`:p.package_weight_grams?`${p.package_label} de ${p.package_weight_grams.toLocaleString('pt-BR')} g`:p.package_label}</p>
   {!p.has_flavors&&<PackPicker p={p} mode={mode} setMode={setMode}/>}
   <div className="price-row"><div>{p.has_flavors&&price?<small>A partir de</small>:null}<strong>{price?money(price):'Sob consulta'}</strong>{price?<small>/{mode==='package'?p.package_label.toLowerCase():'fardo'}</small>:null}</div>{!p.has_flavors&&price?<Quantity value={qty} onChange={setQty}/>:null}</div>
   <button className="btn add-button" disabled={p.has_flavors?!p.available:!available} onClick={()=>p.has_flavors?onDetails(p):onAdd(p,mode,qty)}>{!p.available?'Indisponível':p.has_flavors?'Escolher sabores':!price?'Sob consulta':'Adicionar'}{p.has_flavors?<ChevronRight size={17}/>:<PlusMark/>}</button>
  </div>
 </article>;

}
function PlusMark(){return <span className="plus-mark">+</span>;}
export default function Storefront(){
 const [data,setData]=useState<Catalog|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[cart,setCart]=useState<CartItem[]>([]),[ready,setReady]=useState(false);
 const [line,setLine]=useState('all'),[search,setSearch]=useState(''),[sort,setSort]=useState('default'),[cartOpen,setCartOpen]=useState(false),[detailSelection,setDetail]=useState<Product|null>(null),[detailMode,setDetailMode]=useState<'package'|'bundle'>('package'),[detailQty,setDetailQty]=useState(1),[detailBundles,setDetailBundles]=useState(0);
 const [checkout,setCheckout]=useState(false),[customer,setCustomer]=useState(EMPTY_CUSTOMER),[sending,setSending]=useState(false),[receipt,setReceipt]=useState<{number:string;whatsapp_url:string;message:string;customer_id:string}|null>(null);
 const [profile,setProfile]=useState<CustomerProfile|null>(null),[onboardingOpen,setOnboardingOpen]=useState(false),[restoreError,setRestoreError]=useState(''),[adminView,setAdminView]=useState(false),[portionId,setPortionId]=useState('');
 const [historyOpen,setHistoryOpen]=useState(false);
 const favorites=useFavorites(profile?.id);
 const cartSync=useCartSync(profile?.id,ready,cart,setCart,sending||!!receipt);
 const detail=detailSelection?(data?.products.find(p=>p.id===detailSelection.id)||null):null;
 const detailBundleQty=detail?.bundle_enabled===false?0:detailBundles;
 useEffect(()=>{if(!cartSync.error)return;let cancelled=false;getCatalog().then(c=>{if(!cancelled)setData(c);}).catch(()=>{});return()=>{cancelled=true;};},[cartSync.error]);
 const preferenceQueue=useRef(Promise.resolve());
 function acceptProfile(p:CustomerProfile){try{const owner=localStorage.getItem('yp-cart-owner');if(owner&&owner!==p.id)setCart([]);localStorage.setItem('yp-cart-owner',p.id);}catch{}let old=null,saved=null;try{old=JSON.parse(sessionStore.getItem('yp-submission')||'null');saved=JSON.parse(sessionStore.getItem('yp-receipt')||'null');}catch{}submission.current=old?.customer_id===p.id?old:null;setReceipt(saved?.customer_id===p.id?saved:null);setProfile(p);setPortionId(p.preferred_portion_id||p.portions[0]?.id||'');setCustomer(c=>({...c,company:p.store_name,phone:p.phone,name:p.contact_name||c.name}));setRestoreError('');}
 async function restore(){setRestoreError('');try{const p=await restoreCustomer();if(p){acceptProfile(p);setOnboardingOpen(false);}else{setProfile(null);setCustomer(EMPTY_CUSTOMER);setReceipt(null);submission.current=null;sessionStore.removeItem('yp-receipt');sessionStore.removeItem('yp-submission');let admin=false;try{admin=!!sessionStore.getItem('yp-auth');}catch{}setAdminView(admin);setOnboardingOpen(!admin);}}catch{setRestoreError('Não foi possível carregar os dados da sua loja. Confira a conexão e tente novamente.');setOnboardingOpen(true);}}
 useEffect(()=>{void restore();const sync=(e:StorageEvent)=>{if(e.key==='yp-shop-v1')window.location.reload();};window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync);},[]);
 function editProfile(){setCartOpen(false);setDetail(null);setOnboardingOpen(true);}
 function selectPortion(id:string){setPortionId(id);setProfile(p=>p?{...p,preferred_portion_id:id}:p);resetReceipt();const device_token=readIdentity()?.token;if(profile)preferenceQueue.current=preferenceQueue.current.then(async()=>{await api('customer_preference',{portion_id:id,device_token});}).catch(()=>{toast.error('A simulação foi alterada, mas não foi possível salvar sua preferência para a próxima visita.');});}
 async function switchStore(){try{await customerApi('customer_forget');}catch{toast.error('Não foi possível encerrar este acesso. Tente novamente.');return;}forgetIdentity();setProfile(null);setCart([]);setCustomer(EMPTY_CUSTOMER);resetReceipt();submission.current=null;try{sessionStore.removeItem('yp-submission');}catch{}setCheckout(false);setCartOpen(false);setRestoreError('');setOnboardingOpen(true);}
 const projection=(compact=false)=><ProjectionCard items={resolved} portions={profile?.portions||[]} selected={portionId} onSelect={selectPortion} onEdit={editProfile} compact={compact}/>;
 const submission=useRef<{fingerprint:string;id:string;client_token:string;customer_id:string}|null>(null);
 const load=async()=>{setLoading(true);setError('');try{setData(await getCatalog());}catch{setError('Não foi possível carregar o catálogo. Tente novamente.');}finally{setLoading(false);}};
 useEffect(()=>{void load();try{const stored=JSON.parse(localStorage.getItem(CART_KEY)||'[]');if(Array.isArray(stored))setCart(stored.filter(i=>typeof i.product_id==='string'&&(!i.flavor_id||typeof i.flavor_id==='string')&&['package','bundle'].includes(i.mode)&&Number.isInteger(i.quantity)&&i.quantity>0&&i.quantity<=999));}catch{}setReady(true);track('visit',undefined,true);},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem(CART_KEY,JSON.stringify(cart));}catch{}},[cart,ready]);
 const resolved=useMemo(()=>data?resolveCart(cart,data):[],[cart,data]);const subtotal=resolved.reduce((s,i)=>s+i.unit_price*i.quantity,0);
 const grouped=groupCart(resolved);
 const unresolved=cart.filter(i=>!resolved.some(r=>cartKey(r)===cartKey(i)));
 const cartCount=grouped.length+unresolved.length;
 const invalid=!!data&&(resolved.length!==cart.length||resolved.some(i=>!i.product.available||!i.unit_price||i.mode==='bundle'&&!i.product.bundle_units));
 const products=useMemo(()=>{let list=data?.products.filter(p=>(line==='all'||p.line_id===line)&&normalizeSearch(`${p.name} ${p.sku} ${p.description} ${data.flavors.filter(f=>f.product_id===p.id).map(f=>`${f.name} ${f.sku||''}`).join(' ')}`).includes(normalizeSearch(search)))||[];if(sort==='name')list=list.toSorted((a,b)=>a.name.localeCompare(b.name));if(sort==='price')list=list.toSorted((a,b)=>(startingPrice(a,data!.flavors)??Infinity)-(startingPrice(b,data!.flavors)??Infinity));return list;},[data,line,search,sort]);
 const offer=data&&!cart.some(i=>i.upsell)?cartOffer(data,cart):null;
 const upsellFlavor=data?.flavors.find(f=>f.id===offer?.flavor_id);
 const upsellParent=data?.products.find(p=>p.id===offer?.product_id);
 const upsell=upsellParent?variantProduct(upsellParent,upsellFlavor):undefined;
 useEffect(()=>{if(cartOpen&&offer)track('upsell_view',offer.product_id,true,offer.flavor_id||undefined);},[cartOpen,offer?.product_id,offer?.flavor_id,offer?.rule_id]);
 function resetReceipt(){if(receipt){submission.current=null;sessionStore.removeItem('yp-submission');}setReceipt(null);sessionStore.removeItem('yp-receipt');}
 function addSelection(entries:CartItem[]){
  if(profile&&!cartSync.loaded){toast.error('Aguarde o carregamento do carrinho.');return false;}
  try{let next=cart;for(const entry of entries){if(entry.mode==='bundle'&&data?.products.find(p=>p.id===entry.product_id)?.bundle_enabled===false)throw new Error('Este produto está disponível apenas por pacote.');const previous=next.find(i=>cartKey(i)===cartKey(entry));next=setVariantQuantity(next,entry,entry.mode,(previous?.quantity||0)+entry.quantity);if(entry.upsell&&!previous)next=next.map(i=>cartKey(i)===cartKey(entry)?{...i,upsell:true,upsell_rule_id:entry.upsell_rule_id}:i);}resetReceipt();setCart(next);entries.forEach(i=>track('add_to_cart',i.product_id,false,i.flavor_id||undefined));return true;}catch(e){toast.error(e instanceof Error?e.message:'Confira as quantidades.');return false;}
 }
 function add(p:Product,mode:'package'|'bundle',quantity:number,isUpsell=false,flavor_id?:string,silent=false,upsell_rule_id?:string|null){if(!addSelection([{product_id:p.id,flavor_id:flavor_id||null,mode,quantity,upsell:isUpsell,upsell_rule_id:upsell_rule_id||null}]))return;if(isUpsell)track('upsell_add',p.id,false,flavor_id);if(!silent)toast.success(`${p.name} adicionado ao pedido`,{action:{label:'Ver pedido',onClick:()=>setCartOpen(true)}});}
 function updateGroup(i:CartItem,mode:CartItem['mode'],quantity:number){if(!cartSync.loaded)return;try{if(mode==='bundle'&&quantity>0&&data?.products.find(p=>p.id===i.product_id)?.bundle_enabled===false)throw new Error('Este produto está disponível apenas por pacote.');const next=setVariantQuantity(cart,i,mode,quantity);resetReceipt();setCart(next);}catch(e){toast.error(e instanceof Error?e.message:'Confira a quantidade.');}}
 function removeGroup(i:CartItem){if(!cartSync.loaded)return;resetReceipt();setCart(c=>{const next=c.filter(x=>variantKey(x)!==variantKey(i));return next.some(x=>!x.upsell)?next:next.map(x=>({...x,upsell:false,upsell_rule_id:null}));});}
 function remove(i:CartItem){if(!cartSync.loaded)return;resetReceipt();setCart(c=>{const next=c.filter(x=>cartKey(x)!==cartKey(i));return next.some(x=>!x.upsell)?next:next.map(x=>({...x,upsell:false}));});}
 function convertBundle(i:CartItem){if(profile&&!cartSync.loaded)return;try{const next=convertBundleToPackages(cart,i);resetReceipt();setCart(next);toast.success('Fardos convertidos em pacotes. Confira o pedido.');}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível converter.');}}
 const showDetails=(p:Product)=>{setDetail(p);setDetailMode('package');setDetailQty(1);setDetailBundles(0);track('product_click',p.id);};
 async function send(e:React.FormEvent){e.preventDefault();if(!data||sending||invalid)return;setSending(true);
 try{const cartRevision=await cartSync.flush();const items=resolved.map(i=>({product_id:i.product_id,flavor_id:i.flavor_id||null,mode:i.mode,quantity:i.quantity,unit_price:i.unit_price,upsell:!!i.upsell,upsell_rule_id:i.upsell_rule_id||null}));const fingerprint=JSON.stringify({items,customer,profile:profile?.id,profileVersion:profile?.updated_at,portionId,yields:resolved.map(i=>[i.product.yield_min_grams,i.product.yield_grams])});if(submission.current?.fingerprint!==fingerprint){submission.current={fingerprint,customer_id:profile!.id,id:crypto.randomUUID(),client_token:crypto.randomUUID()};sessionStore.setItem('yp-submission',JSON.stringify(submission.current));}
 const result=await api('order',{...submission.current,cart_revision:cartRevision,session_id:sessionId(),items,customer,customer_device_token:readIdentity()?.token,portion_id:portionId,profile_version:profile?.updated_at});const saved={...result,customer_id:profile!.id};setReceipt(saved);sessionStore.setItem('yp-receipt',JSON.stringify(saved));setCheckout(false);cartSync.close(result.cart_revision);window.location.assign(result.whatsapp_url);
 }catch(e){toast.error(e instanceof Error?e.message:'Não foi possível preparar o pedido.');if(e instanceof PortalError&&(e.status===401||e.status===409)){setCartOpen(false);setCheckout(false);await restore();if(e.status===409)await cartSync.refresh();}try{setData(await getCatalog());}catch{}}finally{setSending(false);}}
 function startCheckout(){if(!profile){editProfile();return;}setCartOpen(true);setCheckout(true);track('checkout',undefined,true);}
 function summary(){return <><div className="summary-top"><ShoppingBag size={19}/><h2>Seu pedido</h2><span className="count">{cartCount}</span></div>{!cart.length?<div className="empty-cart"><p>Escolha os sabores para começar.</p></div>:<><div className="summary-list">{grouped.map(g=><div className="summary-item" key={g.key}><div><strong>{itemName(g.item)}</strong><small>{[g.bundles?`${g.bundles} × fardo`:'',g.packages?`${g.packages} × pacote`:''].filter(Boolean).join(' + ')}</small></div><b>{money(g.total)}</b></div>)}</div><div className="summary-subtotal"><span>Subtotal</span><strong>{money(subtotal)}</strong></div>{projection(true)}<button className="btn primary wide" onClick={()=>setCartOpen(true)} disabled={!data?.settings.ordering_enabled}>Revisar pedido<ArrowRight size={17}/></button></>}</>;}

 return <><Toaster richColors position="top-center"/><header className="site-header"><div className="header-inner"><Brand/><div className="header-actions">
 {profile?<DropdownMenu><DropdownMenuTrigger asChild><button type="button" className="shop-menu-button" aria-label="Minha loja"><Store size={18}/><span>Minha loja</span><ChevronDown size={14}/></button></DropdownMenuTrigger><DropdownMenuContent align="end" sideOffset={10} collisionPadding={12} className="shop-menu-content">
  <DropdownMenuLabel className="shop-menu-identity"><span className="shop-menu-avatar" aria-hidden="true"><Store size={20}/></span><span><small>Minha loja</small><strong>{profile.store_name}</strong></span></DropdownMenuLabel>
  <DropdownMenuSeparator className="shop-menu-separator"/>
  <DropdownMenuItem className="shop-menu-item" onSelect={()=>{setCartOpen(false);setDetail(null);setHistoryOpen(true);}}><ShoppingBag aria-hidden="true"/><span>Meus pedidos</span><ChevronRight className="shop-menu-arrow" aria-hidden="true"/></DropdownMenuItem>
  <DropdownMenuItem className="shop-menu-item" onSelect={editProfile}><Settings2 aria-hidden="true"/><span>Meus preços e dados</span><ChevronRight className="shop-menu-arrow" aria-hidden="true"/></DropdownMenuItem>
  <DropdownMenuSeparator className="shop-menu-separator"/>
  <DropdownMenuItem className="shop-menu-item shop-menu-switch" onSelect={()=>void switchStore()}><ArrowRightLeft aria-hidden="true"/><span>Trocar loja</span></DropdownMenuItem>
 </DropdownMenuContent></DropdownMenu>:adminView?<button className="btn text-button" onClick={editProfile}>Cadastrar loja</button>:null}
 <button className="header-cart" onClick={()=>setCartOpen(true)}><ShoppingBag size={20}/><span>Meu pedido</span><b>{cartCount}</b></button></div></div></header><main className="store-main"><section className="catalog-heading"><h1>Monte seu pedido</h1><a className="catalog-help" href={`https://wa.me/${data?.settings.whatsapp||'554532541200'}`} target="_blank" rel="noreferrer"><Headphones size={18}/><span>Ajuda</span></a></section>
 {receipt&&<div className="receipt-banner"><Check size={20}/><div><strong>Pedido {receipt.number} preparado</strong><p>Envie a mensagem no WhatsApp para nossa equipe receber seu pedido.</p></div><a className="btn secondary" href={receipt.whatsapp_url}>Abrir WhatsApp</a><button className="btn secondary" onClick={()=>{resetReceipt();submission.current=null;sessionStore.removeItem("yp-submission");setCart([]);setCustomer({...EMPTY_CUSTOMER,name:profile?.contact_name||'',company:profile?.store_name||'',phone:profile?.phone||''});}}>Novo pedido</button><button className="icon-button" onClick={resetReceipt} aria-label="Fechar aviso"><X size={17}/></button></div>}
 {data&&!data.settings.ordering_enabled&&<div className="notice-bar"><Clock3 size={18}/><span>Estamos atualizando nosso catálogo. Para fazer um pedido agora, fale com nossa equipe pelo WhatsApp.</span></div>}
 <div className="catalog-layout"><section className="catalog-content"><div className="line-tabs" role="group" aria-label="Filtrar linha"><button className={line==='all'?'selected':''} onClick={()=>setLine('all')}>Todas as linhas</button>{data?.lines.map(l=><button key={l.id} className={line===l.id?'selected':''} onClick={()=>setLine(l.id)}>{l.name}</button>)}</div><div className="catalog-toolbar"><label className="search-box"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar linha ou sabor" aria-label="Buscar linha ou sabor"/>{search&&<button onClick={()=>setSearch('')} aria-label="Limpar busca"><X size={16}/></button>}</label><div className="sort-control"><Choice value={sort} onChange={setSort} label="Ordenar produtos" options={[{value:'default',label:'Ordenar'},{value:'name',label:'Nome do produto'},{value:'price',label:'Menor preço'}]}/></div></div>
 {loading?<div className="products-grid">{[0,1,2].map(i=><Skeleton key={i} className="h-[360px] rounded-2xl"/>)}</div>:error?<div className="empty-state"><Package size={36}/><h2>Não foi possível abrir o catálogo</h2><p>{error}</p><button className="btn primary" onClick={load}>Tentar novamente</button></div>:products.length?<div className="products-grid">{products.map(p=><ProductCard key={p.id} p={p} flavors={data?.flavors||[]} onAdd={add} onDetails={showDetails} enabled={!!data?.settings.ordering_enabled&&(!profile||cartSync.loaded)}/>)}</div>:<div className="empty-state"><Search size={32}/><h2>Nenhum produto encontrado</h2><p>Tente outro nome ou selecione todas as linhas.</p><button className="btn secondary" onClick={()=>{setSearch('');setLine('all');}}>Limpar filtros</button></div>}
 </section><aside className="order-sidebar"><div className="order-summary">{summary()}</div></aside></div></main><footer className="site-footer"><span>Yogomarcas</span><div><a href="/privacidade">Privacidade</a></div></footer>{cart.length>0&&<button className="mobile-cart btn primary" onClick={()=>setCartOpen(true)}><ShoppingBag size={19}/>{cartCount} {cartCount===1?'item':'itens'} no pedido<strong>{money(subtotal)}</strong><ChevronRight size={19}/></button>}
 <Sheet open={!!detail} onOpenChange={v=>{if(!v)setDetail(null);}}><SheetContent className="product-sheet overflow-y-auto w-full sm:max-w-xl"><SheetHeader><SheetTitle>{detail?.name}</SheetTitle><SheetDescription>{detail?.has_flavors?'Escolha os sabores e as quantidades.':'Escolha a quantidade para o pedido.'}</SheetDescription></SheetHeader>{detail&&<div className="detail-body"><Disclosure title={detail.has_flavors?'Sobre esta linha':'Sobre este produto'}><Photo product={detail} large/><p>{detail.description}</p>{detail.package_weight_grams&&!detail.has_flavors&&<p>{detail.package_weight_grams.toLocaleString('pt-BR')} g por {detail.package_label.toLowerCase()}</p>}</Disclosure>{detail.has_flavors?<FlavorPicker key={detail.id} product={detail} flavors={data?.flavors||[]} enabled={!!data?.settings.ordering_enabled&&(!profile||cartSync.loaded)} favorites={favorites.ids} favoritePending={favorites.pending} favoritesReady={favorites.ready} onFavorite={profile?favorites.toggle:undefined} initialSearch={data?.flavors.some(f=>f.product_id===detail.id&&normalizeSearch(f.name).includes(normalizeSearch(search)))?search:''} onAdd={items=>{if(!addSelection(items.map(i=>({product_id:detail.id,flavor_id:i.flavor.id,mode:i.mode,quantity:i.quantity}))))return false;setDetail(null);toast.success('Seleção adicionada ao pedido',{action:{label:'Ver pedido',onClick:()=>setCartOpen(true)}});return true;}}/>:<><p className="small muted">{detail.bundle_enabled===false?'Disponível apenas por pacote.':'1 fardo = 5 pacotes.'}</p><div className="price-row"><strong className="detail-price">{detail.package_price?money(detail.package_price):'Preço sob consulta'}<small className="detail-unit"> / pacote</small></strong></div><DualQuantity allowBundle={detail.bundle_enabled!==false} name={detail.name} packages={detailQty} bundles={detailBundleQty} disabled={!detail.available||!detail.package_price} onChange={(mode,n)=>mode==='bundle'?setDetailBundles(n):setDetailQty(n)}/><button className="btn primary wide" disabled={!data?.settings.ordering_enabled||!!profile&&!cartSync.loaded||!detail.available||!detail.package_price||!detailQty&&!detailBundleQty} onClick={()=>{if(addSelection(([{product_id:detail.id,mode:'package' as const,quantity:detailQty},{product_id:detail.id,mode:'bundle' as const,quantity:detailBundleQty}]).filter(i=>i.quantity>0&&(i.mode!=='bundle'||detail.bundle_enabled!==false)))){setDetail(null);toast.success('Produto adicionado ao pedido');}}}><ShoppingBag size={18}/>Adicionar {money((detailQty+detailBundleQty*5)*(detail.package_price||0))} ao pedido</button></>}</div>}</SheetContent></Sheet>
 <Sheet open={cartOpen} onOpenChange={v=>{setCartOpen(v);if(!v)setCheckout(false);}}><SheetContent className="cart-sheet overflow-y-auto w-full sm:max-w-xl"><SheetHeader><SheetTitle>{checkout?'Finalizar pedido':'Seu pedido'}</SheetTitle><SheetDescription className="sr-only">{checkout?'Informe os dados para o atendimento pelo WhatsApp.':'Confira sabores, quantidades e valores.'}</SheetDescription></SheetHeader><div className="cart-body">{cartSync.recovery&&<div className="notice-bar"><div><p>Há alterações deste aparelho que não foram sincronizadas. Você pode substituir os itens exibidos pelos itens recuperados.</p><button className="btn secondary" onClick={cartSync.recover}>Usar itens deste aparelho</button></div></div>}{profile&&cartSync.error&&<div className="error-box" role="alert">{cartSync.error}<button className="btn secondary" onClick={cartSync.retry}>Sincronizar carrinho</button></div>}{!cart.length?<div className="empty-cart"><ShoppingBag size={48}/><h3>Seu pedido está vazio</h3><button className="btn primary" onClick={()=>setCartOpen(false)}>Escolher produtos</button></div>:<>
 {!checkout&&<><fieldset className="cart-items cart-fieldset" disabled={!!profile&&!cartSync.loaded||sending}>{grouped.some(g=>g.item.product.bundle_enabled!==false)&&<p className="cart-presentation-note">1 fardo = 5 pacotes.</p>}{grouped.map(g=><CartRow key={g.key} group={g} onChange={(mode,q)=>updateGroup(g.item,mode,q)} onRemove={()=>removeGroup(g.item)}/>)}{unresolved.map(i=>{const product=data?.products.find(p=>p.id===i.product_id),flavor=data?.flavors.find(f=>f.id===i.flavor_id&&f.product_id===product?.id),packageVariant=data?resolveCart([{...i,mode:'package',upsell:false}],data)[0]:undefined,blocked=i.mode==='bundle'&&product?.bundle_enabled===false&&!!packageVariant?.product.available&&packageVariant.unit_price>0;return <div className="cart-item" key={cartKey(i)}>{blocked?<><strong>{product.name}{flavor?` · ${flavor.name}`:''}</strong><p className="small muted">Este produto agora é vendido apenas por pacote. {i.quantity} {i.quantity===1?'fardo equivale':'fardos equivalem'} a {i.quantity*5} pacotes.</p></>:<p>Este produto ou sabor saiu do catálogo.</p>}<div className="unavailable-cart-actions">{blocked&&<button type="button" className="btn secondary" onClick={()=>convertBundle(i)}>Trocar por {i.quantity*5} pacotes</button>}<button type="button" className="btn secondary" onClick={()=>remove(i)}>Remover</button></div></div>;})}</fieldset>{upsell&&offer&&<CartSuggestion title={offer.title} description={offer.description} product={upsell} flavor={upsellFlavor} price={offer.price} disabled={!cartSync.loaded} onAdd={()=>add(upsell,'package',1,true,upsellFlavor?.id,false,offer.rule_id)}/>}</>}
 <div className="checkout-total"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><p className="small muted">{data?.settings.notice}</p>{invalid&&<p className="error-box">Um item ficou indisponível ou mudou de condição. Remova o item e selecione novamente no catálogo.</p>}{data&&subtotal<data.settings.minimum_order&&<p className="error-box">Pedido mínimo de {money(data.settings.minimum_order)}. Faltam {money(data.settings.minimum_order-subtotal)}.</p>}
 {!checkout&&projection()}
 {checkout?<form onSubmit={send} className="checkout-form"><div className="checkout-identity"><div><strong>{customer.company}</strong><span>{customer.phone}</span></div><button type="button" onClick={editProfile}>Editar</button></div><div className="form-grid"><Field label="Seu nome" required value={customer.name} onChange={v=>setCustomer({...customer,name:v})} autoComplete="name"/><Field label="Cidade" required value={customer.city} onChange={v=>setCustomer({...customer,city:v})} autoComplete="address-level2"/><label className="field"><span>Estado</span><Choice value={customer.state} onChange={v=>setCustomer({...customer,state:v})} options={STATES.map(s=>({label:s,value:s}))} label="Estado"/></label></div><Disclosure title="Adicionar observação ou código"><Field label="Código do cliente" value={customer.code} onChange={v=>setCustomer({...customer,code:v})}/><label className="field"><span>Observações</span><textarea rows={3} maxLength={1000} value={customer.notes} onChange={e=>setCustomer({...customer,notes:e.target.value})} placeholder="O que precisamos saber?"/></label></Disclosure><p className="small muted">O WhatsApp abrirá com seu pedido pronto para enviar. <a href="/privacidade" target="_blank">Privacidade</a></p><button type="submit" className="btn whatsapp wide" disabled={sending||invalid||!data?.settings.ordering_enabled||subtotal<(data?.settings.minimum_order||0)}>{sending?<LoaderCircle className="spin" size={18}/>:<ShoppingBag size={18}/>}Enviar pelo WhatsApp<ArrowRight size={18}/></button><button type="button" className="btn text-button wide" onClick={()=>setCheckout(false)}>Voltar ao pedido</button></form>:<><button className="btn primary wide" onClick={startCheckout} disabled={invalid||!data?.settings.ordering_enabled||subtotal<(data?.settings.minimum_order||0)}>Continuar<ArrowRight size={18}/></button><button className="btn text-button wide" onClick={()=>setCartOpen(false)}>Continuar comprando</button></>}
 </>}</div></SheetContent></Sheet>{profile&&<CustomerHistory key={profile.id} customerId={profile.id} open={historyOpen} onOpenChange={setHistoryOpen} hasCart={cart.length>0} onRepeat={(items,catalog)=>{if(!cartSync.loaded){toast.error('Aguarde o carregamento do carrinho.');return false;}try{const merged=mergeRepeat(cart,items);resetReceipt();setData(catalog);setCart(merged);setCartOpen(true);setCheckout(false);items.forEach(i=>track('add_to_cart',i.product_id,false,i.flavor_id||undefined));toast.success('Pedido carregado. Confira os itens antes de continuar.');return true;}catch(e){toast.error(e instanceof Error?e.message:'Não foi possível repetir.');return false;}}}/>}<CustomerOnboarding open={onboardingOpen} profile={profile} onOpenChange={setOnboardingOpen} onSaved={p=>{resetReceipt();submission.current=null;sessionStore.removeItem('yp-submission');acceptProfile(p);}} restoreError={restoreError} onRetry={()=>void restore()} allowClose={adminView}/></>;
}
function CartRow({group:g,onChange,onRemove}:{group:CartGroup;onChange:(mode:CartItem['mode'],q:number)=>void;onRemove:()=>void}){return <div className="cart-item"><div className="cart-item-title"><div><strong>{itemName(g.item)}</strong><small>{g.units} {g.units===1?'pacote':'pacotes'} no total{g.item.upsell?' · Sugestão':''}</small></div><button className="icon-button" onClick={onRemove} aria-label={`Remover ${itemName(g.item)}`}><Trash2 size={17}/></button></div><div className="cart-item-bottom"><DualQuantity allowBundle={g.item.product.bundle_enabled!==false} name={itemName(g.item)} packages={g.packages} bundles={g.bundles} onChange={onChange}/><strong>{money(g.total)}</strong></div></div>;}

function Field({label,value,onChange,required=false,type='text',autoComplete,readOnly=false}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean;type?:string;autoComplete?:string;readOnly?:boolean}){return <label className="field"><span>{label}{required?' *':''}</span><input readOnly={readOnly} required={required} type={type} value={value} onChange={e=>onChange(e.target.value)} autoComplete={autoComplete} maxLength={200} minLength={required&&type==='text'?2:undefined}/></label>;}
